import OrderStatusBadge from "./OrderStatusBadge";
import { useEffect,useState } from "react";
import { isAxiosError } from "axios";
import { CheckCircle2,CupSoda,LayoutGrid,List,Minus,Plus,RefreshCw,Search,ShoppingBag,ShoppingCart,Trash2 } from "lucide-react";
import Navbar from "../../components/layout/Navbar";
import { useAuth } from "../../app/AuthContext";
import { userCan } from "../../app/roleAccess";
import { currentBusinessDate } from "../../utils/businessDate";
import { getOrderCategories,getOrderCatalog,quoteOrder,checkoutOrder,getOrderHistoryDetail,type CartRequestItem,type OrderCategory,type OrderCatalogItem,type OrderQuote,type OrderReceipt } from "../../api/orderCatalog.api";
const money=(value:string|number)=>`Rp ${new Intl.NumberFormat("id-ID",{maximumFractionDigits:0}).format(Number(value))}`;
const errorMessage=(e:unknown)=>isAxiosError<{message?:string}>(e)?e.response?.data?.message||"Gagal memproses order.":"Gagal memproses order.";
type CartEntry={menu:OrderCatalogItem;quantity:number};
export default function OrderPage(){
 const {user}=useAuth();const canOrder=userCan(user,"orders","create");
 const [categories,setCategories]=useState<OrderCategory[]>([]);const [category,setCategory]=useState("");const [search,setSearch]=useState("");const [view,setView]=useState<"grid"|"table">("grid");
 const [items,setItems]=useState<OrderCatalogItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [categoryError,setCategoryError]=useState("");const [page,setPage]=useState(0);const [total,setTotal]=useState(0);const [refresh,setRefresh]=useState(0);
 const [quantities,setQuantities]=useState<Record<string,number>>({});const [cart,setCart]=useState<CartEntry[]>([]);const [quote,setQuote]=useState<OrderQuote|null>(null);const [quoteError,setQuoteError]=useState("");const [checking,setChecking]=useState(false);const [saving,setSaving]=useState(false);const [requestID,setRequestID]=useState(()=>crypto.randomUUID());const [retry,setRetry]=useState(false);const [receipt,setReceipt]=useState<OrderReceipt|null>(null);
 const cartPayload=():CartRequestItem[]=>cart.map(entry=>({recipe_id:entry.menu.recipe_id,price_snapshot_id:entry.menu.price_snapshot_id,quantity:entry.quantity}));
 useEffect(()=>{let active=true;setCategoryError("");getOrderCategories().then(r=>{if(active)setCategories(r.data||[])}).catch(e=>{if(active)setCategoryError(errorMessage(e))});return()=>{active=false}},[refresh]);
 useEffect(()=>{let active=true;setLoading(true);setError("");getOrderCatalog({start:page*12,limit:12,name:search,category_id:category}).then(r=>{if(active){setItems(r.data||[]);setTotal(r.total||0)}}).catch(e=>{if(active){setError(errorMessage(e));setItems([]);setTotal(0)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[page,category,search,refresh]);
 useEffect(()=>{
  let active=true;setQuote(null);setQuoteError("");if(!cart.length){setChecking(false);return;}
  setChecking(true);const timer=setTimeout(()=>{quoteOrder(cart.map(entry=>({recipe_id:entry.menu.recipe_id,price_snapshot_id:entry.menu.price_snapshot_id,quantity:entry.quantity}))).then(r=>{if(active)setQuote(r.data)}).catch(e=>{if(active)setQuoteError(errorMessage(e))}).finally(()=>{if(active)setChecking(false)});},250);
  return()=>{active=false;clearTimeout(timer)};
 },[cart,refresh]);
 function changeCart(next:CartEntry[]){if(saving)return;setRetry(false);setQuote(null);setQuoteError("");setRequestID(crypto.randomUUID());setCart(next);setReceipt(null)}
 function add(menu:OrderCatalogItem){const qty=quantities[menu.recipe_id]||1;const existing=cart.find(e=>e.menu.recipe_id===menu.recipe_id);if(!menu.ready||qty+(existing?.quantity||0)>menu.max_quantity)return;changeCart(existing?cart.map(e=>e.menu.recipe_id===menu.recipe_id?{menu,quantity:e.quantity+qty}:e):[...cart,{menu,quantity:qty}]);setQuantities(q=>({...q,[menu.recipe_id]:1}))}
 function adjust(id:string,delta:number){const entry=cart.find(e=>e.menu.recipe_id===id);if(!entry)return;const qty=entry.quantity+delta;if(qty<1){changeCart(cart.filter(e=>e.menu.recipe_id!==id));return};const live=items.find(e=>e.recipe_id===id);if(qty>(live?.max_quantity??entry.menu.max_quantity))return;changeCart(cart.map(e=>e.menu.recipe_id===id?{...e,quantity:qty}:e))}
 async function submit(){if(saving||(!quote&&!retry)||(checking&&!retry)||!canOrder)return;setSaving(true);setError("");try{const result=await checkoutOrder(requestID,cartPayload());setRetry(false);setReceipt(result.data);setCart([]);setQuote(null);setRequestID(crypto.randomUUID());setRefresh(v=>v+1)}catch(e){setRetry(true);setError(errorMessage(e));setRefresh(v=>v+1)}finally{setSaving(false)}}
 useEffect(()=>{if(!receipt||receipt.status==="COMPLETED")return;let active=true;const timer=setInterval(()=>{getOrderHistoryDetail(receipt.id).then(r=>{if(active)setReceipt(r.data)}).catch(()=>{});},10000);return()=>{active=false;clearInterval(timer)}},[receipt?.id,receipt?.status]);
 const quantityControls=(item:OrderCatalogItem)=>{
  const inCart=cart.find(e=>e.menu.recipe_id===item.recipe_id)?.quantity||0;const remaining=Math.max(0,item.max_quantity-inCart);const qty=quantities[item.recipe_id]||1;const available=item.ready&&remaining>0;
  return <div className="mt-4 flex items-center gap-2"><label className="sr-only" htmlFor={`qty-${item.recipe_id}`}>Jumlah {item.name} {item.version}</label><input id={`qty-${item.recipe_id}`} type="number" min="1" max={Math.max(1,remaining)} step="1" value={qty} disabled={!available||saving||!canOrder} onChange={e=>setQuantities(q=>({...q,[item.recipe_id]:Math.max(1,Math.min(remaining,Math.floor(Number(e.target.value)||1)))}))} className="h-10 w-16 rounded-lg border bg-white px-2 text-center text-sm disabled:opacity-40"/><button onClick={()=>add(item)} disabled={!available||qty>remaining||saving||!canOrder} className="flex h-10 flex-1 items-center justify-center gap-2 rounded-lg bg-[var(--color-brand-primary)] px-3 text-sm font-semibold text-white disabled:bg-stone-100 disabled:text-stone-400"><Plus size={16}/>{!item.ready?"Stock kosong":remaining===0?"Batas stok":!canOrder?"Akses baca":"Tambah"}</button></div>;
 };
 const estimated=cart.reduce((sum,e)=>sum+Number(e.menu.selling_price)*e.quantity,0);
 return <div className="min-h-screen bg-[var(--color-brand-cream)]"><Navbar orderMode/><main className="mx-auto max-w-[1800px] p-5 sm:p-8">
  <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 grid size-12 place-items-center rounded-2xl bg-[var(--color-brand-soft)] text-[var(--color-brand-primary)]"><ShoppingBag size={24}/></div><h1 className="font-serif text-3xl font-bold text-[var(--color-brand-primary)]">Order pelanggan</h1><p className="mt-2 text-sm text-stone-500">Pilih menu dan jumlahnya, lalu tambahkan ke pesanan.</p><p className="mt-1 text-xs text-stone-500">Bisnis day · {currentBusinessDate()}</p></div><button onClick={()=>setRefresh(v=>v+1)} disabled={loading||saving} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-semibold disabled:opacity-40"><RefreshCw size={17}/>Perbarui menu</button></header>
  {(error||categoryError)&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error||categoryError}</p>}
  {receipt&&<section role="status" className="mb-5 rounded-2xl border border-green-200 bg-green-50 p-5 text-green-800"><div className="flex items-center gap-2 font-bold"><CheckCircle2 size={21}/>Pesanan diterima · {money(receipt.total)}<OrderStatusBadge status={receipt.status}/></div><p className="mt-1 break-all text-xs">{receipt.order_number}</p><p className="mt-2 text-sm">Stok sudah berkurang sesuai jumlah pesanan.</p>{receipt.items.map(line=><p key={line.recipe_id} className="mt-1 text-sm">{line.quantity} × {line.name} · {line.version} — {money(line.total)}</p>)}</section>}
  <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
  <section className="min-w-0 overflow-hidden rounded-2xl border border-stone-200 bg-white"><header className="flex flex-wrap items-center justify-between gap-4 border-b p-5"><div><h2 className="font-bold">Menu tersedia</h2><p className="mt-1 text-xs text-stone-500">{total} versi menu</p></div><div className="flex flex-wrap items-center gap-3"><div role="group" aria-label="Tampilan menu order" className="inline-flex rounded-full border border-[var(--color-brand-sage)] bg-[var(--color-brand-cream)] p-1">{(["grid","table"] as const).map(mode=>{const Icon=mode==="grid"?LayoutGrid:List;return <button key={mode} aria-pressed={view===mode} onClick={()=>setView(mode)} className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-sm font-semibold ${view===mode?"bg-[var(--color-brand-primary)] text-white":"text-[var(--color-brand-primary)]"}`}><Icon size={15}/>{mode==="grid"?"Grid":"Table"}</button>})}</div><label className="flex h-11 w-full items-center gap-2 rounded-xl border border-[var(--color-brand-sage)] px-3 sm:w-56"><Search size={17} className="text-stone-400"/><input aria-label="Cari menu order" placeholder="Cari menu atau versi…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label></div></header>
  <nav aria-label="Kategori menu order" className="flex gap-2 overflow-x-auto border-b px-5 py-4">{[{category_id:"",name:"Semua menu",menu_count:0},...categories].map(c=><button key={c.category_id} type="button" aria-pressed={category===c.category_id} onClick={()=>{setCategory(c.category_id);setPage(0)}} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-semibold ${category===c.category_id?"border-[var(--color-brand-primary)] bg-[var(--color-brand-primary)] text-white":"border-[var(--color-brand-sage)] text-[var(--color-brand-primary)] hover:bg-[var(--color-brand-soft)]"}`}>{c.name}{c.category_id&&<span className="ml-2 opacity-65">{c.menu_count}</span>}</button>)}</nav>
  {loading?<p className="p-16 text-center text-stone-500">Memuat menu dan stok…</p>:!items.length?<div className="p-16 text-center"><CupSoda size={32} className="mx-auto mb-3 text-stone-400"/><p className="font-semibold">Belum ada menu tersedia</p><p className="mt-2 text-sm text-stone-500">Menu tampil setelah harga penjualannya aktif.</p></div>:view==="grid"?<div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=><article key={item.price_snapshot_id} className={`flex flex-col rounded-2xl border p-5 ${item.ready?"border-[var(--color-brand-sage)] bg-[var(--color-brand-surface)]":"border-stone-200 bg-stone-50"}`}><div className="mb-4 flex items-center justify-between gap-2"><span className="grid size-11 place-items-center rounded-full bg-[var(--color-brand-soft)] text-[var(--color-brand-primary)]"><CupSoda size={23}/></span><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.ready?"bg-green-50 text-green-700":"bg-red-50 text-red-700"}`}>{item.ready?"Tersedia":"Stock kosong"}</span></div><p className="text-xs text-stone-500">{item.category_name}</p><h3 className="mt-1 text-lg font-bold text-[var(--color-brand-primary)]">{item.name}</h3><p className="mt-1 text-sm font-semibold text-stone-600">{item.version}</p>{item.description&&<p className="mt-2 line-clamp-2 text-sm text-stone-500">{item.description}</p>}<p className="mt-auto pt-5 text-xl font-bold text-[var(--color-brand-primary)]">{money(item.selling_price)}</p>{quantityControls(item)}</article>)}</div>:<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr>{["Menu","Harga jual","Stok","Jumlah"].map(label=><th key={label} className="p-4">{label}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.price_snapshot_id} className="border-t"><td className="p-4"><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-stone-500">{item.category_name} · {item.version}</p></td><td className="p-4 font-bold">{money(item.selling_price)}</td><td className={`p-4 text-xs font-semibold ${item.ready?"text-green-700":"text-red-700"}`}>{item.ready?"Tersedia":"Stock kosong"}</td><td className="w-52 p-4">{quantityControls(item)}</td></tr>)}</tbody></table></div>}
  <footer className="flex flex-wrap items-center justify-between gap-3 border-t p-5 text-sm text-stone-500"><span>Halaman {page+1} dari {Math.max(1,Math.ceil(total/12))}</span><div className="flex gap-2"><button disabled={page===0||loading} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Sebelumnya</button><button disabled={(page+1)*12>=total||loading} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Berikutnya</button></div></footer></section>
  <aside className="rounded-2xl border border-stone-200 bg-white xl:sticky xl:top-5"><header className="flex items-center gap-2 border-b p-5 font-bold"><ShoppingCart size={20}/>Pesanan<span className="ml-auto text-sm text-stone-500">{cart.reduce((n,e)=>n+e.quantity,0)} item</span></header><div className="max-h-[55dvh] overflow-y-auto p-5">{!cart.length?<p className="py-8 text-center text-sm text-stone-500">Tambahkan menu ke pesanan.</p>:cart.map(entry=><div key={entry.menu.recipe_id} className="mb-4 border-b pb-4 last:mb-0 last:border-0 last:pb-0"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{entry.menu.name}</p><p className="mt-1 text-xs text-stone-500">{entry.menu.version} · {money(entry.menu.selling_price)}</p></div><button disabled={saving} onClick={()=>changeCart(cart.filter(e=>e.menu.recipe_id!==entry.menu.recipe_id))} aria-label={`Hapus ${entry.menu.name} dari pesanan`} className="rounded-lg p-2 text-red-600 hover:bg-red-50 disabled:opacity-40"><Trash2 size={16}/></button></div><div className="mt-3 flex items-center justify-between gap-2"><div className="flex items-center gap-3"><button disabled={saving} onClick={()=>adjust(entry.menu.recipe_id,-1)} aria-label={`Kurangi ${entry.menu.name}`} className="rounded border p-1.5 disabled:opacity-40"><Minus size={14}/></button><span className="text-sm font-semibold">{entry.quantity}</span><button disabled={saving} onClick={()=>adjust(entry.menu.recipe_id,1)} aria-label={`Tambah ${entry.menu.name}`} className="rounded border p-1.5 disabled:opacity-40"><Plus size={14}/></button></div><strong className="text-sm">{money(Number(entry.menu.selling_price)*entry.quantity)}</strong></div></div>)}</div><footer className="border-t p-5">{quoteError&&<p role="alert" className="mb-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{quoteError}</p>}<div className="mb-4 flex items-center justify-between font-bold"><span>Total</span><span className="text-xl text-[var(--color-brand-primary)]">{money(quote?.total??estimated)}</span></div>{checking&&<p role="status" className="mb-3 text-xs text-stone-500">Mengecek jumlah dan stok…</p>}<button disabled={(!quote&&!retry)||(checking&&!retry)||saving||!canOrder||!cart.length} onClick={()=>void submit()} className="w-full rounded-xl bg-[var(--color-brand-primary)] py-3 font-semibold text-white disabled:opacity-40">{saving?"Memproses pesanan…":retry?"Coba pesan lagi":"Pesan"}</button></footer></aside>
  </div></main></div>;
}
