import {useAuth} from "../../app/AuthContext";
import {userCan} from "../../app/roleAccess";
import OrderStatusBadge from "./OrderStatusBadge";
import {useEffect,useState} from "react";
import {Eye,RefreshCw,Search,ShoppingBag,X} from "lucide-react";
import {isAxiosError} from "axios";
import Sidebar from "../../components/layout/Sidebar";
import Navbar from "../../components/layout/Navbar";
import {getOrderHistory,getOrderHistoryDetail,updateOrderStatus,type HistoryOrder} from "../../api/orderCatalog.api";
import {currentBusinessDate,formatBusinessDate} from "../../utils/businessDate";
const money=(v:string|number)=>`Rp ${new Intl.NumberFormat("id-ID",{maximumFractionDigits:0}).format(Number(v))}`;
const message=(e:unknown)=>isAxiosError<{message?:string}>(e)?e.response?.data?.message||"Gagal memuat pesanan.":"Gagal memuat pesanan.";
export default function OrderHistoryPage(){
 const {user}=useAuth();const canUpdate=userCan(user,"orders","update");const [updating,setUpdating]=useState(false);
 async function advanceOrder(){if(!detail||updating||!canUpdate||detail.status==="COMPLETED")return;setUpdating(true);setDetailError("");try{const result=await updateOrderStatus(detail.id,detail.status,detail.status==="WAITING"?"PROCESSING":"COMPLETED");setDetail(result.data);setRefresh(v=>v+1)}catch(e){setDetailError(message(e));setRefresh(v=>v+1)}finally{setUpdating(false)}}
 const [sidebar,setSidebar]=useState(false),[date,setDate]=useState(currentBusinessDate),[search,setSearch]=useState(""),[page,setPage]=useState(0),[refresh,setRefresh]=useState(0);
 const [rows,setRows]=useState<HistoryOrder[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const [detail,setDetail]=useState<HistoryOrder|null>(null),[detailID,setDetailID]=useState<string|null>(null),[detailError,setDetailError]=useState("");
 useEffect(()=>{let active=true;setLoading(true);setError("");getOrderHistory({start:page*10,limit:10,date,search}).then(r=>{if(active){setRows(r.data||[]);setTotal(r.total||0)}}).catch(e=>{if(active){setError(message(e));setRows([]);setTotal(0)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[page,date,search,refresh]);
 useEffect(()=>{if(!detailID)return;let active=true;setDetail(null);setDetailError("");getOrderHistoryDetail(detailID).then(r=>{if(active)setDetail(r.data)}).catch(e=>{if(active)setDetailError(message(e))});return()=>{active=false}},[detailID]);
 useEffect(()=>{if(!detailID)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setDetailID(null)};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close)}},[detailID]);
 useEffect(()=>{if(updating)return;let active=true;const timer=setInterval(()=>{setRefresh(v=>v+1);if(detailID)getOrderHistoryDetail(detailID).then(r=>{if(active)setDetail(r.data)}).catch(()=>{});},10000);return()=>{active=false;clearInterval(timer)}},[detailID,updating]);
 return <div className="flex min-h-screen bg-[var(--color-brand-cream)]"><Sidebar isOpen={sidebar} onClose={()=>setSidebar(false)}/><section className="min-w-0 flex-1"><Navbar onMenuClick={()=>setSidebar(true)}/><main className="p-5 sm:p-8"><header className="mb-7 flex items-end justify-between gap-4"><div><ShoppingBag className="mb-3 text-[var(--color-brand-primary)]"/><h1 className="text-3xl font-bold">Riwayat Pesanan</h1><p className="mt-2 text-stone-500">Pesanan tersimpan dan rincian item berdasarkan bisnis day.</p></div><button onClick={()=>setRefresh(v=>v+1)} aria-label="Perbarui pesanan" className="rounded-xl border bg-white p-3"><RefreshCw size={20}/></button></header>
 <div className="overflow-hidden rounded-2xl border border-stone-200 bg-white"><div className="flex flex-col gap-4 border-b p-5 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="font-bold">Daftar pesanan</h2><p className="text-sm text-stone-500">{total} pesanan ditemukan</p></div><div className="flex flex-col gap-3 sm:flex-row"><label className="text-sm font-semibold">Bisnis day<input type="date" value={date} onChange={e=>{setDate(e.target.value);setPage(0)}} className="mt-1 block rounded-xl border p-3 font-normal"/></label><label className="flex items-center gap-2 self-end rounded-xl border p-3"><Search size={18} className="text-stone-400"/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="Cari nomor atau pembuat…" aria-label="Cari pesanan" className="min-w-0 outline-none"/></label></div></div>
 {error&&<p role="alert" className="m-5 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-stone-500"><tr>{["Nomor pesanan","Bisnis day / waktu","Pembuat","Jumlah item","Total","Status","Detail"].map(x=><th key={x} className="whitespace-nowrap px-5 py-4">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-8 text-center text-stone-500">Memuat pesanan…</td></tr>:!rows.length?<tr><td colSpan={7} className="p-8 text-center text-stone-500">Belum ada pesanan.</td></tr>:rows.map(row=><tr key={row.id} className="border-t hover:bg-stone-50"><td className="max-w-xs break-all px-5 py-4 font-semibold">{row.order_number}</td><td className="whitespace-nowrap px-5 py-4">{formatBusinessDate(row.business_date)}<p className="mt-1 text-xs text-stone-500">{new Date(row.created_at).toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Jakarta"})} WIB</p></td><td className="px-5 py-4">{row.created_by}</td><td className="px-5 py-4">{row.item_count}</td><td className="whitespace-nowrap px-5 py-4 font-bold">{money(row.total)}</td><td className="px-5 py-4"><OrderStatusBadge status={row.status}/></td><td className="px-5 py-4"><button aria-label={`Detail ${row.order_number}`} onClick={()=>setDetailID(row.id)} className="rounded-lg border p-2 text-[var(--color-brand-primary)] hover:bg-green-50"><Eye size={18}/></button></td></tr>)}</tbody></table></div><footer className="flex items-center justify-between gap-3 border-t p-5 text-sm"><span>Halaman {page+1} dari {Math.max(1,Math.ceil(total/10))}</span><div className="flex gap-2"><button disabled={page===0||loading} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Sebelumnya</button><button disabled={(page+1)*10>=total||loading} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Berikutnya</button></div></footer></div>
 </main></section>{detailID&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={()=>setDetailID(null)}><div role="dialog" aria-modal="true" aria-labelledby="order-detail-title" className="max-h-[90dvh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-xl" onClick={e=>e.stopPropagation()}><header className="flex items-center justify-between border-b p-5"><h2 id="order-detail-title" className="text-xl font-bold">Detail pesanan</h2><button autoFocus aria-label="Tutup detail" onClick={()=>setDetailID(null)} className="rounded-lg p-2"><X/></button></header><div className="p-5">{detailError&&<p role="alert" className="mb-3 rounded-lg bg-red-50 p-3 text-red-700">{detailError}</p>}{!detail?<p>Memuat detail…</p>:<><p className="break-all font-bold">{detail.order_number}</p><p className="mt-2 text-sm text-stone-500">{formatBusinessDate(detail.business_date)} · {detail.created_by}</p><div className="mt-4 flex items-center justify-between gap-3"><OrderStatusBadge status={detail.status}/>{canUpdate&&detail.status!=="COMPLETED"&&<button disabled={updating} onClick={()=>void advanceOrder()} className="rounded-xl bg-[var(--color-brand-primary)] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{updating?"Memperbarui…":detail.status==="WAITING"?"Proses pesanan":"Selesaikan pesanan"}</button>}</div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-stone-50"><tr>{["Menu / versi","Jumlah","Harga","Subtotal"].map(label=><th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{detail.items.map(item=><tr key={item.recipe_id} className="border-b"><td className="p-3 font-semibold">{item.name}<p className="mt-1 text-xs font-normal text-stone-500">{item.version}</p></td><td className="p-3">{item.quantity}</td><td className="whitespace-nowrap p-3">{money(item.unit_price)}</td><td className="whitespace-nowrap p-3 font-bold">{money(item.total)}</td></tr>)}</tbody></table></div><div className="mt-5 flex justify-between rounded-xl bg-green-50 p-4 font-bold"><span>Total</span><span>{money(detail.total)}</span></div></>}</div></div></div>}</div>;
}
