import { createContext, useContext, useMemo, type ReactNode } from "react";

export type Language = "id";

type LanguageContextValue = {
  language: Language;
  t: (text: string) => string;
};

const translations: Record<string, string> = {
  "Ingredient ID": "ID Bahan",
  "Price ID": "ID Harga",
  Address: "Alamat",
  Retry: "Coba lagi",
  "Could not load ingredient details.": "Gagal memuat detail bahan.",
  "Open navigation": "Buka navigasi",
  Notifications: "Notifikasi",
  "Open account menu": "Buka menu akun",
  Profile: "Profil",
  Logout: "Keluar",
  "Close profile": "Tutup profil",
  "Team Member": "Anggota Tim",
  Email: "Email",
  Phone: "Telepon",
  Link: "Link",
  "Open link": "Buka link",
  "Link must be a valid http:// or https:// URL":
    "Link harus berupa URL http:// atau https:// yang valid",
  "Confirm logout?": "Konfirmasi keluar?",
  "You’ll need to sign in again to access the C.R.E.M.A dashboard.":
    "Kamu perlu masuk lagi untuk mengakses dashboard C.R.E.M.A.",
  Cancel: "Batal",
  "Logging out...": "Sedang keluar...",
  "Close menu": "Tutup menu",
  "Search sidebar menus": "Cari menu sidebar",
  "Search menus": "Cari menu",
  "Search menus...": "Cari menu...",
  "Clear menu search": "Bersihkan pencarian menu",
  "Main navigation": "Navigasi utama",
  Overview: "Ringkasan",
  "Business Days": "Bisnis Harian",
  "User Management": "Manajemen User",
  "Role Management": "Manajemen Role",
  "Unit Management": "Satuan isi",
  "Ingredient Management": "Bahan",
  Suppliers: "Supplier",
  Packaging: "Satuan kemasan",
  "Brand / Type": "Brand / Type",
  "Back to ingredients": "Kembali ke bahan",
  "Choose the active price for this ingredient":
    "Kelola pilihan harga aktif dan nonaktif untuk bahan ini.",
  "Active price": "Harga aktif",
  "Ingredient price history": "Riwayat harga bahan",
  "No ingredient prices yet": "Belum ada harga bahan",
  "Ingredient has no active price. Select an active price in ingredient details first.":
    "Bahan belum punya harga aktif. Pilih harga aktif di detail bahan terlebih dahulu.",
  "Price follows the active ingredient price":
    "Harga mengikuti harga aktif bahan; transaksi lama memakai harga tersimpan",
  "Ingredient price saved": "Harga bahan berhasil disimpan",
  "Use as active price": "Gunakan sebagai harga aktif",
  "Enter a valid price and date":
    "Isi harga valid (maksimal 2 desimal) dan tanggal",
  "Price per packaging unit. Used as the default for new supplier shopping records.":
    "Harga per satuan kemasan. Dipakai sebagai harga awal saat mencatat belanja supplier baru.",
  "Activating a price automatically deactivates the previous price. Saved shopping records keep their prices.":
    "Mengaktifkan harga akan menonaktifkan harga sebelumnya. Harga pada belanja yang sudah disimpan tetap.",
  "Save this price as active? The previous active price will become inactive.":
    "Simpan sebagai harga aktif? Harga aktif sebelumnya akan dinonaktifkan.",
  "Save this inactive price?": "Simpan harga ini sebagai nonaktif?",
  "Deactivate ingredient price": "Nonaktifkan harga bahan",
  "Activate ingredient price": "Aktifkan harga bahan",
  "Deactivate this price? No price will be selected.":
    "Nonaktifkan harga ini? Bahan tidak akan memiliki harga aktif.",
  "Use this price? The previous active price will become inactive.":
    "Gunakan harga ini? Harga aktif sebelumnya akan dinonaktifkan.",
  "Master Price & PAR": "Master Harga & PAR",
  "Could not load ingredient prices.": "Gagal memuat riwayat harga bahan.",
  "Add ingredient price": "Tambah harga bahan",
  "Update ingredient price": "Update harga bahan",
  "Create ingredient price": "Buat harga bahan",
  "Delete this price? Saved PO prices remain unchanged. Deleting an active price leaves no active price.":
    "Hapus harga ini? Harga PO tersimpan tetap. Menghapus harga aktif membuat bahan tidak punya harga aktif.",
  "Price already used in PO":
    "Harga sudah dipakai di PO dan tidak bisa dihapus",
  "Delete this unused price? Deleting an active price leaves no active price.":
    "Hapus harga yang belum dipakai ini? Menghapus harga aktif membuat bahan tidak punya harga aktif.",
  "Delete ingredient price": "Hapus harga bahan",
  "All ingredient prices": "Semua harga bahan",
  "prices found": "harga ditemukan",
  "Search price...": "Cari harga...",
  "Loading prices...": "Memuat harga...",
  "No prices found": "Harga tidak ditemukan",
  "Create this ingredient price?": "Buat harga bahan ini?",
  "Update this ingredient price?": "Update harga bahan ini?",
  "Delete this ingredient price permanently?":
    "Hapus harga bahan ini permanen?",
  "Could not delete ingredient price.": "Gagal menghapus harga bahan.",
  "Unit Price": "Harga Satuan",
  "Effective Date": "Tanggal Berlaku",
  "Package Qty": "Qty Kemasan",
  "Content Qty": "Isi",
  Content: "Isi",
  required: "wajib diisi",
  "Stock Count": "Stock Opname",
  "Current Stock": "Stock Saat Ini",
  "Stock In": "Stock Masuk",
  Purchasing: "Purchasing",
  "Stock Adjustments": "Penyesuaian Stock",
  "Stock Movements": "Stock Movement",
  "Menu Items": "HPP",
  Dashboard: "Dashboard",
  Users: "User",
  Roles: "Role",
  Units: "Satuan isi",
  Ingredients: "Bahan",
  Categories: "Kategori",
  Products: "Produk",
  Recipes: "Resep",
  "Recipe Items": "Item Resep",
  Inventory: "Inventori",
  Menu: "Menu",
  "Master Data": "Data Master",
  "No menus found": "Menu tidak ditemukan",
  "Try another keyword.": "Coba kata kunci lain.",
  "Manage access roles and review assigned users.":
    "Kelola role akses dan cek user yang terhubung.",
  "Add role": "Tambah role",
  "Create role": "Buat role",
  "Create this role?": "Buat role ini?",
  "Update this role name?": "Update nama role ini?",
  "All roles": "Semua role",
  "roles found": "role ditemukan",
  "Search role...": "Cari role...",
  Role: "Role",
  Usage: "Pemakaian",
  Action: "Aksi",
  "Loading roles...": "Memuat role...",
  "No roles found": "Role tidak ditemukan",
  Assigned: "Terpasang",
  Unused: "Belum dipakai",
  "Manage users": "Kelola user",
  "Update role": "Update role",
  "Have assigned users": "Masih punya user",
  "Delete role": "Hapus role",
  "Select all": "Pilih semua",
  "Select unit": "Pilih satuan",
  "Delete selected": "Hapus terpilih",
  "Delete selected units": "Hapus satuan terpilih",
  "Delete selected units permanently?":
    "Hapus satuan terpilih secara permanen?",
  "Could not delete selected units.": "Gagal menghapus satuan terpilih.",
  "Delete selected packaging": "Hapus kemasan terpilih",
  "Delete selected packaging permanently?":
    "Hapus kemasan terpilih secara permanen?",
  "Could not delete selected packaging.": "Gagal menghapus kemasan terpilih.",
  Export: "Export",
  "Reference only. This weight does not change the stock remaining.": "Hanya informasi. Berat ini tidak mengurangi atau mengubah stok sisa.",
  "Ingredient reference information": "Informasi bahan",
  "Enter the remaining stock directly, as in the Stock Remaining column in Excel.": "Masukkan stok sisa langsung, seperti kolom Stock Sisa di Excel.",
  "Stock remaining": "Stok sisa",
  "Leave subcategory empty to show all ingredients in this category.": "Kosongkan subkategori untuk menampilkan semua bahan dalam kategori ini.",
  "Net count": "Hitung bersih",
  "containers": "kemasan",
  "gross": "total",
  "Stock value": "Nilai stok",
  "Weighing": "Timbangan & kemasan",
  "Some items have no saved price. Their value is not included in this total.": "Sebagian bahan belum memiliki harga tersimpan. Nilainya belum termasuk dalam total ini.",
  "Value uses the unit price saved with each count item.": "Nilai menggunakan harga satuan yang disimpan bersama setiap record opname.",
  "Stock value at count": "Nilai stok saat opname",
  "Enter goods only, excluding containers. Zero means counted and empty.": "Masukkan jumlah barang tanpa kemasan. Angka nol berarti sudah dihitung dan stok kosong.",
  "Fill the weighing fields to calculate net stock": "Lengkapi data timbangan untuk menghitung stok bersih",
  "Container weight exceeds gross weight": "Berat kemasan melebihi berat total timbangan",
  "Net stock": "Stok bersih",
  "Use the measured conversion for this liquid. Grams and millilitres are not automatically equal.": "Gunakan faktor konversi hasil pengukuran bahan cair ini. Gram tidak otomatis sama dengan mililiter.",
  "Grams per stock unit": "Gram per satuan stok",
  "Containers on scale": "Jumlah kemasan di timbangan",
  "Empty container weight (g)": "Berat satu kemasan kosong (g)",
  "Gross weight (g)": "Berat total di timbangan (g)",
  "Weigh all counted goods together with their containers. Only count containers on the scale.": "Timbang seluruh barang yang dihitung bersama kemasannya. Isi jumlah kemasan yang ikut berada di timbangan.",
  "For this unit, enter the net stock count directly.": "Untuk satuan ini, masukkan jumlah stok bersih secara langsung.",
  "Weigh with containers": "Timbang bersama kemasan",
  "Edit purchase order": "Ubah PO",
  "Transaction details": "Rincian transaksi",
  "Order details and delivery information": "Rincian pesanan & informasi pengiriman",
  "Stock added": "Stok sudah ditambahkan",
  "Delivery": "Penerimaan",
  "Save receipt and add stock": "Simpan penerimaan & tambah stok",
  "Saving records this delivery and adds its goods to stock. The remaining order stays open.": "Menyimpan penerimaan ini langsung menambah stok barang yang datang. Sisa pesanan tetap menunggu penerimaan berikutnya.",
  "item types in this delivery": "jenis barang pada penerimaan ini",
  "Review and save": "Periksa lalu simpan",
  "Still waiting after this delivery": "Sisa setelah penerimaan ini",
  "Enter goods received now": "Isi barang yang datang",
  "Check again": "Periksa lagi",
  "Open Business Day page": "Buka halaman Business Day",
  "Stock enters the Business Day for the receipt date. Open that date first, or ask the person managing Business Day.": "Stok masuk dicatat ke Business Day sesuai tanggal penerimaan. Buka tanggal tersebut terlebih dahulu, atau hubungi pengelola Business Day.",
  "Receipt date must have an open Business Day": "Tanggal penerimaan harus memiliki Business Day yang OPEN",
  "No open Business Day for this date": "Business Day tanggal ini belum OPEN",
  "Business Day is open for this date": "Business Day tanggal ini sudah OPEN",
  "Checking Business Day...": "Memeriksa Business Day...",
  "Example: remaining goods arrive tomorrow": "Contoh: sisa barang dikirim besok",
  "Choose the receipt date": "Tentukan tanggal penerimaan",
  "Enter only goods arriving now. Leave undelivered items empty.": "Isi hanya jumlah barang yang datang kali ini. Barang yang belum datang boleh dikosongkan.",
  "Record this delivery": "Catat penerimaan kali ini",
  "Complete": "Lengkap",
  "Record a delivery": "Catat barang datang",
  "Goods progress": "Progres barang",
  "item types not fully received": "jenis barang belum lengkap",
  "recorded deliveries": "penerimaan tercatat",
  "Still waiting": "Masih ditunggu",
  "Already received": "Sudah diterima",
  "ordered item types": "jenis barang dipesan",
  "Compare the order with goods already received. Record each delivery separately.": "Lihat barang yang sudah datang dan yang masih ditunggu. Catat setiap kedatangan barang secara terpisah.",
  "Confirm delivered goods through the supplier PO.": "Konfirmasi barang yang datang melalui PO supplier.",
  "Sections filter the item list. Daily submission applies to all sections.": "Bagian memfilter daftar bahan. Submit harian berlaku untuk semua bagian.",
  "Record Adjustment when needed. If there is none, continue to Closing Stock.": "Catat penyesuaian jika diperlukan. Jika tidak ada, lanjutkan ke Stock Akhir.",
  "Submit this section only? Other sections can continue counting.": "Submit bagian ini saja? Bagian lain tetap bisa melanjutkan pengisian.",
  "Submit each section separately. Completed sections are locked; other sections can continue.": "Submit tiap bagian secara terpisah. Bagian yang selesai terkunci; bagian lain tetap bisa diisi.",
  "Submit opening stock for this section first": "Submit Stock Awal bagian ini terlebih dahulu.",
  "This stock count section is already submitted": "Bagian Stock Opname ini sudah disubmit.",
  "Closing stock for this section is already submitted": "Stock Akhir bagian ini sudah disubmit.",
  "Yellow: physical remaining stock entered by staff": "Kuning: stok sisa fisik yang diisi staff",
  "Gray: system reference, read only": "Abu-abu: informasi sistem, tidak diinput",
  "Copy previous closing stock": "Salin Stock Akhir sebelumnya",
  "Copy previous submitted closing quantities into this section? Existing items are kept.": "Salin jumlah Stock Akhir yang sudah disubmit ke bagian ini? Item yang sudah diisi tetap dipertahankan.",
  "Items copied": "Item disalin",
  "Could not copy stock.": "Gagal menyalin stok.",
  "No previous submitted closing stock for this section": "Belum ada Stok Akhir sebelumnya yang sudah disubmit untuk bagian ini. Isi Stok Awal secara manual terlebih dahulu.",
  "Copy is only available for opening stock": "Salin stok hanya tersedia untuk Stok Awal.",
  "This stock count section cannot be edited": "Bagian Stock Opname ini tidak dapat diubah. Pastikan masih berstatus draft dan hari operasional masih terbuka.",
  "Choose a stock count section": "Pilih bagian Stock Opname terlebih dahulu.",
  "Stock count not found": "Data Stock Opname tidak ditemukan.",
  "Stock count section not found": "Bagian Stock Opname tidak ditemukan.",
  "Stock count is already submitted": "Stock Opname sudah disubmit.",
  "Business day is already closed": "Hari operasional sudah ditutup.",
  "Enter remaining stock for every item in this section": "Isi stok sisa untuk semua item di bagian ini sebelum submit.",
  "Ingredient category must belong to Barista, Kitchen, or Waiters": "Kategori item harus termasuk bagian Barista, Kitchen, atau Waiters.",
  "Submit Barista, Kitchen, and Waiters separately first": "Submit bagian Barista, Kitchen, dan Waiters masing-masing terlebih dahulu.",
  "Some items have an unsupported category; correct them before submission": "Ada item dengan kategori yang belum didukung. Perbaiki kategorinya sebelum submit.",
  "Submit all draft Stock Adjustment records first": "Submit semua draft Penyesuaian Stok terlebih dahulu.",
  "Submit closing stock for Barista, Kitchen, and Waiters before closing the business day": "Submit Stok Akhir Barista, Kitchen, dan Waiters sebelum menutup hari operasional.",
  "Could not process stock count section": "Gagal memproses bagian Stock Opname. Coba lagi.",
  "Invalid section notes": "Catatan bagian tidak valid atau terlalu panjang.",
  "Invalid section input": "Data bagian Stock Opname tidak valid.",
  "Out of stock": "Stok habis",
  "Low stock": "Stok rendah",
  "In stock": "Stok tersedia",
  "List": "List",
  "Grid": "Grid",
  "View mode": "Mode tampilan",
  "View details": "Lihat detail",
  "Stock count section": "Bagian Stock Opname",
  "All sections": "Semua bagian",
  "Submit stock count for all sections? Make sure Barista, Kitchen, and Waiters are complete.": "Submit Stock Opname untuk semua bagian? Pastikan Barista, Kitchen, dan Waiters sudah lengkap.",
  "PO receiving progress": "Progres penerimaan PO",
  "PO already has receipts and cannot be edited": "PO sudah memiliki penerimaan dan tidak bisa diubah.",
  "PO not found": "PO tidak ditemukan",
  "Invalid receipt input": "Data penerimaan tidak valid",
  "Invalid received quantity": "Jumlah diterima tidak valid",
  "Item does not belong to PO": "Barang bukan bagian PO ini",
  "Duplicate receipt item": "Barang penerimaan duplikat",
  "Receipt request has different data": "Permintaan penerimaan sudah digunakan dengan data berbeda",
  "Received stock exceeds supported decimal precision": "Jumlah stok diterima maksimal tiga angka desimal",
  "PO content unit differs from current stock unit": "Satuan isi PO berbeda dengan satuan stok bahan saat ini",
  "Closing stock is already submitted": "Stok penutupan sudah disubmit",
  "Receipt date requires an open business day": "Tanggal penerimaan harus memiliki hari operasional terbuka",
  "Received quantity exceeds remaining order": "Jumlah diterima melebihi sisa pesanan",
  "Confirming receipt immediately posts Stock In. Use an open business day.": "Konfirmasi langsung mencatat stok masuk. Gunakan tanggal hari operasional yang masih terbuka.",
  "Enter received quantities": "Isi jumlah barang yang diterima",
  "Could not receive PO": "Gagal menyimpan penerimaan PO",
  "Could not load PO receiving": "Gagal memuat penerimaan PO",
  "Goods received and stock updated": "Barang diterima dan stok berhasil ditambahkan",
  "Confirm receipt": "Konfirmasi penerimaan",
  "Receipt date": "Tanggal penerimaan",
  "Receipt history": "Riwayat penerimaan",
  "Receive now": "Diterima sekarang",
  "Received total": "Total penerimaan",
  "Order total": "Total pemesanan",
  "Remaining": "Sisa",
  "Ordered": "Dipesan",
  "Receive goods": "Terima barang",
  "Awaiting receipt": "Menunggu penerimaan",
  "Ordering vs receiving": "Pemesanan vs Penerimaan",
  Import: "Import",
  "Importing...": "Import...",
  "Import finished": "Import selesai",
  Detail: "Detail",
  "Import detail": "Detail import",
  Success: "Berhasil",
  Failed: "Gagal",
  Row: "Baris",
  "Code, name, and unit type are required":
    "Kode, nama, dan type satuan isi wajib diisi",
  "Code and name are required": "Kode dan nama wajib diisi",
  "Duplicate code in import file": "Kode duplikat di file import",
  "Duplicate name in import file": "Nama duplikat di file import",
  "Duplicate ingredient variant in import file": "Bahan dengan nama, jumlah isi, dan satuan isi yang sama duplikat di file import.",
  "Invalid supplier status": "Status supplier tidak valid",
  "Supplier updated successfully": "Supplier berhasil diperbarui",
  "You do not have permission to update suppliers":
    "Anda tidak memiliki izin memperbarui supplier",
  "You do not have permission to create suppliers":
    "Anda tidak memiliki izin membuat supplier",
  "Could not prepare supplier import":
    "Tidak dapat membaca file atau memuat data supplier untuk impor",
  "Brand type is used by ingredients": "Brand/type sedang digunakan oleh bahan",
  "Invalid brand type status": "Status brand/type tidak valid",
  "Brand type updated successfully": "Brand/type berhasil diperbarui",
  "You do not have permission to update brand types":
    "Anda tidak memiliki izin memperbarui brand/type",
  "You do not have permission to create brand types":
    "Anda tidak memiliki izin membuat brand/type",
  "Could not prepare brand type import":
    "Tidak dapat membaca file atau memuat data brand/type untuk impor",
  "Imported successfully": "Berhasil diimport",
  "Import failed": "Import gagal",
  "Unit code already exists": "Kode satuan isi sudah ada",
  "Unit name already exists": "Nama satuan isi sudah ada",
  "Invalid unit input": "Data satuan isi tidak valid",
  "Packaging code already exists": "Kode satuan kemasan sudah ada",
  "Packaging name already exists": "Nama satuan kemasan sudah ada",
  "Invalid packaging input": "Data satuan kemasan tidak valid",
  "Internal server error": "Terjadi kesalahan server",
  "Could not read import file.": "File import tidak bisa dibaca.",
  "Delete this role permanently?": "Hapus role ini permanen?",
  Confirm: "Konfirmasi",
  Page: "Halaman",
  of: "dari",
  Limit: "Limit",
  Previous: "Sebelumnya",
  Next: "Berikutnya",
  "Only Admin and HRIS Admin can access this page.":
    "Hanya Admin dan HRIS Admin yang bisa mengakses halaman ini.",
  "Create a new access role.": "Buat role akses baru.",
  "Role name": "Nama role",
  "Menu permissions": "Permission menu",
  "menus selected": "menu dipilih",
  Read: "Lihat",
  Create: "Tambah",
  Update: "Ubah",
  Delete: "Hapus",
  All: "Semua",
  "Read is required by enabled permissions":
    "Read wajib aktif karena permission lain menyala",
  "Saving...": "Menyimpan...",
  Save: "Simpan",
  "Assigned users": "User terpasang",
  "Loading users...": "Memuat user...",
  "This role is not assigned to any users.":
    "Role ini belum dipasang ke user mana pun.",
  "Unnamed user": "User tanpa nama",
  "You cannot remove your own admin role":
    "Kamu tidak bisa menghapus role admin milik sendiri",
  "Remove user from role": "Hapus user dari role",
  "Only admin can change admin role assignments":
    "Hanya admin yang bisa mengubah pemasangan role admin",
  "Add users": "Tambah user",
  "Assign the selected users to this role?":
    "Pasang user yang dipilih ke role ini?",
  "All users are already assigned.": "Semua user sudah terpasang.",
  "Add selected": "Tambah yang dipilih",
  "Remove user": "Hapus user",
  "Remove this user from the role?": "Hapus user ini dari role?",
  Close: "Tutup",
  "Could not load roles.": "Gagal memuat role.",
  "Action failed.": "Aksi gagal.",
  "Could not delete role.": "Gagal menghapus role.",
  "Could not load assigned users.": "Gagal memuat user terpasang.",
  "Could not assign selected users.": "Gagal memasang user yang dipilih.",
  "Could not remove user from role.": "Gagal menghapus user dari role.",
  "No items yet": "Belum ada item",
  "Loading items...": "Memuat item...",
  "Loading products...": "Memuat produk...",
  "Loading recipes...": "Memuat resep...",
  "Loading suppliers...": "Memuat supplier...",
  "Loading ingredients...": "Memuat bahan...",
  "Loading units...": "Memuat satuan...",
  "Loading packaging...": "Memuat satuan kemasan...",
  "Loading stock counts...": "Memuat stock opname...",
  "Loading stock receipts...": "Memuat stock masuk...",
  "Loading stock adjustments...": "Memuat penyesuaian stock...",
  "Loading movements...": "Memuat Stock Movement...",
  "No stock movement history found.": "Riwayat Stock Movement belum ditemukan.",
  "All items": "Semua item",
  "items found": "item ditemukan",
  "Item": "Item",
  "Search item...": "Cari item...",
  "No items found": "Item tidak ditemukan",
  "No users found": "User tidak ditemukan",
  "No products found": "Produk tidak ditemukan",
  "No categories found": "Kategori tidak ditemukan",
  "No ingredients found": "Bahan tidak ditemukan",
  "No suppliers found": "Supplier tidak ditemukan",
  "No units found": "Satuan isi tidak ditemukan",
  "No packaging found": "Satuan kemasan tidak ditemukan",
  "Search adjustment...": "Cari penyesuaian...",
  "Search receipt...": "Cari penerimaan...",
  "Search ingredient...": "Cari bahan...",
  "Search supplier...": "Cari supplier...",
  "Search unit...": "Cari satuan isi...",
  "Search packaging...": "Cari satuan kemasan...",
  "Search category...": "Cari kategori...",
  "Search product...": "Cari produk...",
  "Search menu item...": "Cari menu item...",
  "Ingredient or reference...": "Bahan atau referensi...",
  "Add item": "Tambah item",
  "Update item": "Update item",
  "Delete item": "Hapus item",
  "Add product": "Tambah produk",
  "Update product": "Update produk",
  "Delete product": "Hapus produk",
  "Add category": "Tambah kategori",
  "Update category": "Update kategori",
  "Delete category": "Hapus kategori",
  "Add ingredient": "Tambah bahan",
  "Update ingredient": "Update bahan",
  "Delete ingredient": "Hapus bahan",
  "Add supplier": "Tambah supplier",
  "Update supplier": "Update supplier",
  "Delete supplier": "Hapus supplier",
  "Add unit": "Tambah satuan isi",
  "Update unit": "Update satuan isi",
  "Delete unit": "Hapus satuan isi",
  "Add packaging": "Tambah satuan kemasan",
  "Update packaging": "Update satuan kemasan",
  "Delete packaging": "Hapus satuan kemasan",
  Name: "Nama",
  Description: "Deskripsi",
  Status: "Status",
  Active: "Aktif",
  Inactive: "Nonaktif",
  Price: "Harga",
  Quantity: "Qty",
  Type: "Tipe",
  Reason: "Alasan",
  Date: "Tanggal",
  Notes: "Catatan",
  Product: "Produk",
  Category: "Kategori",
  Ingredient: "Bahan",
  Supplier: "Supplier",
  Unit: "Satuan isi",
  "Business day": "Bisnis harian",
  "Created by": "Dibuat oleh",
  "Submitted by": "Disubmit oleh",
  "Open Stock In": "Buka Stock Masuk",
  "Select supplier": "Pilih supplier",
  "Could not load suppliers": "Gagal memuat supplier",
  "Could not load suppliers.": "Gagal memuat supplier.",
  "Phone must start with 08 and contain 10–13 digits only":
    "Nomor telepon harus diawali 08 dan hanya berisi 10–13 digit angka",
  "Select ingredient category first": "Pilih kategori bahan terlebih dahulu",
  "Back to suppliers": "Kembali ke supplier",
  "Supplier details": "Detail supplier",
  "Supplier ingredients": "Bahan dari supplier",
  "Latest effective prices": "Harga aktif yang dipilih di detail bahan",
  "No supplier ingredients found": "Belum ada bahan dari supplier ini",
  "Supplier transaction history": "Riwayat transaksi supplier",
  "transactions found": "transaksi ditemukan",
  "Loading transaction history...": "Memuat riwayat transaksi...",
  "No supplier transactions yet": "Belum ada transaksi supplier",
  "Purchase order": "Purchase order",
  "Goods receipt": "Penerimaan barang",
  "Open transaction": "Buka transaksi",
  "No transaction items": "Belum ada barang dalam transaksi",
  "Receipt prices are not recorded":
    "Harga dan total tidak dicatat pada penerimaan barang ini.",
  "Partially received": "Diterima sebagian",
  Received: "Diterima",
  "Could not load supplier details": "Tidak dapat memuat detail supplier",
  "Could not load supplier catalog": "Tidak dapat memuat bahan supplier",
  "Could not load supplier history": "Tidak dapat memuat riwayat supplier",
  "Supplier not found": "Supplier tidak ditemukan",
  "Record supplier shopping": "Catat belanja supplier",
  "Edit shopping record": "Ubah catatan belanja",
  "Shopping record": "Catatan belanja",
  Recorded: "Tercatat",
  "Purchase number": "Nomor PO",
  "Delivery date": "Tanggal pengiriman",
  "Payment method": "Metode bayar",
  "Supplier bank account": "Rekening supplier",
  "Ship to": "Tujuan pengiriman",
  Recipient: "Penerima",
  "Supplier information": "Informasi pemasok (supplier)",
  "Shipping information": "Alamat pengiriman (ship to)",
  "Shipping address": "Alamat pengiriman",
  "Shipping phone": "Telepon pengiriman",
  "Product description": "Deskripsi produk",
  "Packaging / Unit": "Kemasan / Satuan",
  "Enter purchased quantities; zero-quantity items are excluded":
    "Isi qty barang yang dibeli. Barang dengan qty 0 tidak ikut disimpan.",
  "Enter a quantity for at least one item":
    "Isi qty minimal satu barang yang dibeli",
  "Invalid quantity or price": "Qty atau harga tidak valid",
  "Delivery date cannot precede purchase date":
    "Tanggal pengiriman tidak boleh sebelum tanggal belanja",
  "Purchase number already exists for this supplier":
    "Nomor PO sudah digunakan untuk supplier ini",
  "Check shopping dates, items, quantities and prices":
    "Periksa tanggal, barang, qty, dan harga belanja. Barang harus aktif dan milik supplier ini.",
  "Could not save shopping record": "Catatan belanja tidak dapat disimpan",
  "Shopping record saved": "Catatan belanja berhasil disimpan",
  "selected items": "barang dipilih",
  "Ingredient subcategory": "Subkategori bahan",
  "Ingredient subcategories": "Subkategori bahan",
  "Select ingredient subcategory": "Pilih subkategori bahan",
  "No subcategories": "Belum ada subkategori",
  "All subcategories": "Semua subkategori",
  "Back to ingredient categories": "Kembali ke kategori bahan",
  "Manage ingredient groups within this category":
    "Kelola kelompok bahan di dalam kategori ini",
  "Add subcategory": "Tambah subkategori",
  "Edit subcategory": "Ubah subkategori",
  "Delete subcategory": "Hapus subkategori",
  "Delete this subcategory permanently?":
    "Hapus subkategori ini secara permanen?",
  "Update subcategory status": "Ubah status subkategori",
  "Update subcategory status?": "Ubah status subkategori ini?",
  "Subcategory name already exists":
    "Nama subkategori sudah ada dalam kategori ini",
  "Subcategory is used by ingredients":
    "Subkategori sedang digunakan oleh bahan atau brand/type",
  "Save changes to this subcategory?": "Simpan perubahan subkategori ini?",
  "Create this subcategory?": "Buat subkategori ini?",
  "Search subcategory...": "Cari subkategori...",
  "Subcategories found": "subkategori ditemukan",
  "Invalid subcategory import format":
    "Format import tidak sesuai. Gunakan file export subkategori bahan.",
  "Subcategory import category mismatch":
    "Kategori bahan tidak sesuai dengan halaman subkategori ini",
  "Subcategory name is too long": "Nama subkategori maksimal 150 karakter",
  "Subcategory saved": "Subkategori berhasil disimpan",
  "Subcategories updated": "Subkategori berhasil diperbarui",
  "Could not load ingredient subcategories":
    "Tidak dapat memuat subkategori bahan",
  "Invalid ingredient subcategory":
    "Subkategori tidak sesuai kategori bahan atau tidak aktif",
  "Name is required": "Nama wajib diisi",
  "Good morning": "Selamat pagi",
  "Good afternoon": "Selamat siang",
  "Good evening": "Selamat sore",
  "Good night": "Selamat malam",
  User: "User",
  "Here’s what’s happening at your coffee shop today.":
    "Ini ringkasan aktivitas kedai kopi kamu hari ini.",
  "+ New order": "+ Pesanan baru",
  "Today’s revenue": "Pendapatan hari ini",
  "Total orders": "Total pesanan",
  "Active products": "Produk aktif",
  "New customers": "Pelanggan baru",
  "4 low stock": "4 stock menipis",
  "Revenue overview": "Ringkasan pendapatan",
  "Performance over the last 7 days": "Performa 7 hari terakhir",
  "Recent orders": "Pesanan terbaru",
  "Latest store activity": "Aktivitas toko terbaru",
  Paid: "Lunas",
  Mon: "Sen",
  Tue: "Sel",
  Wed: "Rab",
  Thu: "Kam",
  Fri: "Jum",
  Sat: "Sab",
  Sun: "Min",
  "Track operational dates for daily, monthly, and yearly reports.":
    "Kelola operasional harian untuk laporan harian, bulanan, dan tahunan.",
  "Business day already exists": "Operasional harian sudah ada",
  "Open business day": "Buka operasional harian",
  "Operational Days": "Operasional Harian",
  "business days found": "operasional harian ditemukan",
  "All status": "Semua status",
  Open: "Buka",
  Closed: "Tutup",
  "Opened By": "Dibuka Oleh",
  "Opened At": "Dibuka Pada",
  "Closed By": "Ditutup Oleh",
  "Closed At": "Ditutup Pada",
  "Loading business days...": "Memuat operasional harian...",
  "No business days found": "Operasional harian tidak ditemukan",
  "Submit all draft Stock In first": "Submit semua draft Stock Masuk dulu",
  "Submit all draft Stock Adjustment first":
    "Submit semua draft Penyesuaian Stock dulu",
  "Close business day": "Tutup operasional harian",
  "Submit closing stock first": "Submit closing stock dulu",
  "Delete stock count first": "Hapus stock opname dulu",
  "Open day": "Buka operasional",
  "Close day": "Tutup operasional",
  "Delete day": "Hapus operasional",
  "Open business day for": "Buka operasional harian untuk",
  "Close business day for": "Tutup operasional harian untuk",
  "Delete business day for": "Hapus operasional harian untuk",
  "This is only allowed when it has no operational records.":
    "Ini hanya bisa dilakukan kalau belum ada catatan operasional.",
  "Could not load business days.": "Gagal memuat operasional harian.",
  "Could not open business day.": "Gagal membuka operasional harian.",
  "Could not close business day.": "Gagal menutup operasional harian.",
  "Could not delete business day.": "Gagal menghapus operasional harian.",
  "Could not load inventory counts.": "Gagal memuat stock opname.",
  "Opening Stock": "Stock Awal",
  "Closing Stock": "Stock Akhir",
  "Physical stock before operational activities":
    "Stock fisik sebelum operasional dimulai",
  "Physical stock after operational activities":
    "Stock fisik setelah operasional selesai",
  "Waiting for stock count": "Menunggu stock opname",
  "Submit opening stock": "Submit stock awal",
  "View closing stock": "Lihat stock akhir",
  "Review stock movement": "Cek Stock Movement stock",
  Done: "Selesai",
  Draft: "Draft",
  "Counted by": "Dihitung oleh",
  Submitted: "Disubmit",
  View: "Lihat",
  Today: "Hari ini",
  "Daily workflow": "Alur harian",
  "Stock count complete": "Stock opname selesai",
  "Continue daily inventory": "Lanjutkan inventori harian",
  "Start with Opening Stock": "Mulai dari Stock Awal",
  "Opening and Closing Stock have been submitted.":
    "Stock Awal dan Stock Akhir sudah disubmit.",
  "Record Stock In or Adjustment when needed. If there is none, continue to Closing Stock.":
    "Catat Stock Masuk atau Penyesuaian jika perlu. Kalau tidak ada, lanjut ke Stock Akhir.",
  "Count physical stock before operational activities begin.":
    "Hitung stock fisik sebelum operasional dimulai.",
  "Count beginning stock.": "Hitung stock awal.",
  "Not submitted": "Belum disubmit",
  "Use only when goods arrive.": "Gunakan hanya saat barang datang.",
  Optional: "Opsional",
  Adjustment: "Penyesuaian",
  "Correct stock when needed.": "Koreksi stock jika diperlukan.",
  Movement: "Stock Movement",
  "Review the ledger.": "Cek kartu stock.",
  Review: "Cek",
  "Count ending stock.": "Hitung stock akhir.",
  "Stock count tasks": "Task stock opname",
  "Opening and closing counts for this business day.":
    "Hitung stock awal dan akhir untuk operasional harian ini.",
  "No stock counts found for this date":
    "Stock opname untuk tanggal ini tidak ditemukan",
  "No business day found for this date":
    "Bisnis harian untuk tanggal ini belum dibuat",
  "Could not load stock receipts.": "Gagal memuat stock masuk.",
  "Please select a supplier.": "Pilih supplier dulu.",
  "Open a business day and submit Opening Stock before creating stock in.":
    "Buka operasional harian dan submit Stock Awal sebelum membuat Stock Masuk.",
  "Save stock in draft": "Simpan draft Stock Masuk",
  "Save this stock in as a draft? You can add items and submit it from the detail page.":
    "Simpan Stock Masuk ini sebagai draft? Item bisa ditambahkan dan disubmit dari halaman detail.",
  "Save Draft": "Simpan Draft",
  "Draft saved successfully.": "Draft berhasil disimpan.",
  "Could not load stock count detail.": "Gagal memuat detail stock opname.",
  "Could not save draft.": "Gagal menyimpan draft.",
  Submit: "Submit",
  "Submit this stock count?": "Submit stock opname ini?",
  "Stock count submitted successfully.": "Stock opname berhasil disubmit.",
  "Could not submit stock count.": "Gagal submit stock opname.",
  "Update this stock count item?": "Update item stock opname ini?",
  "Add this stock count item?": "Tambah item stock opname ini?",
  "Could not save stock count item.": "Gagal menyimpan item stock opname.",
  "Delete this stock count item?": "Hapus item stock opname ini?",
  "Could not delete stock count item.": "Gagal menghapus item stock opname.",
  Opening: "Stock Awal",
  Closing: "Stock Akhir",
  "Submitted at": "Disubmit pada",
  "Example: counted after morning prep, all dry goods checked.":
    "Contoh: dihitung setelah persiapan pagi, semua bahan kering dicek.",
  "Stock In record(s) are still DRAFT. Submit all Stock In for this business day before submitting Closing Stock.":
    "record Stock Masuk masih DRAFT. Submit semua Stock Masuk untuk operasional harian ini sebelum submit Stock Akhir.",
  "Stock Count Items": "Item Stock Opname",
  items: "item",
  Minimum: "Minimum",
  LOW: "RENDAH",
  OK: "OK",
  "Actual quantity": "Qty aktual",
  "Example: 1 bag opened, remaining stock already weighed.":
    "Contoh: 1 bag dibuka, sisa stock sudah ditimbang.",
  "Current quantity from opening stock and submitted stock movements.":
    "Jumlah saat ini dari Stock Awal dan Stock Movement stock yang sudah disubmit.",
  "Could not load current stock.": "Gagal memuat stock saat ini.",
  "Could not load current stock detail.": "Gagal memuat detail stock saat ini.",
  Current: "Saat Ini",
  "Loading current stock...": "Memuat stock saat ini...",
  "No current stock found": "Stock saat ini tidak ditemukan",
  "Low Stock": "Stock Rendah",
  Sufficient: "Cukup",
  "Minimum Stock": "Stock Minimum",
  "Difference Above Minimum": "Selisih di Atas Minimum",
  "Difference Below Minimum": "Selisih di Bawah Minimum",
  "Today's Stock Summary": "Ringkasan Stock Hari Ini",
  "Business Day": "Operasional Harian",
  "Calculated from Opening Stock": "Dihitung dari Stock Awal",
  "Taken from Closing Stock": "Diambil dari Stock Akhir",
  "Current Stock is calculated from Opening Stock plus submitted movements because Closing Stock has not been submitted.":
    "Stock Saat Ini dihitung dari Stock Awal ditambah Stock Movement yang sudah disubmit karena Stock Akhir belum disubmit.",
  "Current Stock is taken from submitted Closing Stock.":
    "Stock Saat Ini diambil dari Stock Akhir yang sudah disubmit.",
  Formula: "Rumus",
  "Stock Out": "Stock Keluar",
  Adjustments: "Penyesuaian",
  ORDER_USAGE: "Pemakaian Resep",
  WASTE: "Waste",
  ADJUSTMENT_IN: "Penyesuaian Masuk",
  ADJUSTMENT_OUT: "Penyesuaian Keluar",
  Reconciliation: "Rekonsiliasi",
  "Compare system expected closing with physical closing stock.":
    "Bandingkan stock akhir sistem dengan stock fisik yang dihitung.",
  "Could not load reconciliation.": "Gagal memuat rekonsiliasi.",
  "Loading reconciliation...": "Memuat rekonsiliasi...",
  "No reconciliation data found": "Data rekonsiliasi tidak ditemukan",
  "Reviewed Items": "Item Dicek",
  "Variance Items": "Item Selisih",
  "Reconciliation Status": "Status Rekonsiliasi",
  "Ready to Review": "Siap Direview",
  "Waiting for Closing Stock": "Menunggu Stock Akhir",
  "Expected Closing": "Stock Akhir Sistem",
  "Physical Closing": "Stock Akhir Fisik",
  Variance: "Selisih",
  Matched: "Sesuai",
  Waiting: "Menunggu",
  "Delete stock in": "Hapus Stock Masuk",
  "Delete this empty stock in record?": "Hapus data Stock Masuk kosong ini?",
  "Could not delete stock receipt.": "Gagal menghapus Stock Masuk.",
  "Trace supplier purchases, receipts, and received items.":
    "Lacak pembelian supplier, penerimaan, dan item yang diterima.",
  "You do not have permission to create purchasing records":
    "Kamu tidak punya akses untuk membuat data purchasing",
  "You do not have permission to update purchasing records.":
    "Kamu tidak punya akses untuk mengubah data purchasing.",
  "You do not have permission to delete purchasing records":
    "Kamu tidak punya akses untuk menghapus data purchasing",
  "Add purchase": "Tambah Purchasing",
  "Purchase Receipts": "Data Purchasing",
  "Purchase Items": "Item Purchasing",
  "Track incoming inventory receipts and received items.":
    "Catat barang masuk dan item yang diterima.",
  "Open a business day first": "Buka operasional harian dulu",
  "Submit Opening Stock first": "Submit Stock Awal dulu",
  "Add stock in": "Tambah Stock Masuk",
  "Stock Receipts": "Data Stock Masuk",
  "records found": "data ditemukan",
  "Stock in can only be added when this business day is open.":
    "Stock Masuk hanya bisa ditambah saat operasional harian ini masih buka.",
  "Open a business day before adding stock in.":
    "Buka operasional harian sebelum menambah Stock Masuk.",
  "Submit Opening Stock before adding or changing stock in.":
    "Submit Stock Awal sebelum menambah atau mengubah Stock Masuk.",
  Receipt: "Penerimaan",
  "Created At": "Dibuat Pada",
  "No stock receipts yet": "Belum ada Stock Masuk",
  "Remove all items before deleting this stock in":
    "Hapus semua item sebelum menghapus Stock Masuk ini",
  "Business Date": "Tanggal Bisnis",
  "Purchase Date": "Tanggal Purchasing",
  "Used for daily purchasing tracking":
    "Dipakai untuk tracking purchasing harian",
  "Auto from current open business day":
    "Otomatis dari operasional harian yang sedang buka",
  "Supplier *": "Supplier *",
  "Example: delivery received complete, invoice checked.":
    "Contoh: barang diterima lengkap, invoice sudah dicek.",
  "Could not load stock adjustments.": "Gagal memuat penyesuaian stock.",
  "Reason is required.": "Alasan wajib diisi.",
  "Open a business day and submit Opening Stock before creating stock adjustment.":
    "Buka operasional harian dan submit Stock Awal sebelum membuat Penyesuaian Stock.",
  "Save stock adjustment draft": "Simpan draft Penyesuaian Stock",
  "Save this stock adjustment as a draft?":
    "Simpan Penyesuaian Stock ini sebagai draft?",
  "Delete stock adjustment": "Hapus Penyesuaian Stock",
  "Delete this empty stock adjustment record?":
    "Hapus data Penyesuaian Stock kosong ini?",
  "Could not delete stock adjustment.": "Gagal menghapus Penyesuaian Stock.",
  "Stock Adjustment": "Penyesuaian Stock",
  "Record approved inventory corrections.":
    "Catat koreksi stock yang sudah disetujui.",
  "Add adjustment": "Tambah Penyesuaian",
  "Stock adjustment can only be added when this business day is open.":
    "Penyesuaian Stock hanya bisa ditambah saat operasional harian ini masih buka.",
  "Open a business day before adding stock adjustment.":
    "Buka operasional harian sebelum menambah Penyesuaian Stock.",
  "Submit Opening Stock before adding or changing stock adjustment.":
    "Submit Stock Awal sebelum menambah atau mengubah Penyesuaian Stock.",
  "No stock adjustments yet": "Belum ada Penyesuaian Stock",
  "Remove all items before deleting this adjustment":
    "Hapus semua item sebelum menghapus penyesuaian ini",
  "Add stock adjustment": "Tambah Penyesuaian Stock",
  "Reason *": "Alasan *",
  "Could not load stock movements.": "Gagal memuat Stock Movement stock.",
  "Order Usage": "Pemakaian Order",
  Waste: "Waste",
  "Inventory quantity changes": "Perubahan jumlah inventori",
  "Stock Movement": "Stock Movement",
  "Stock movement history from submitted stock activity.":
    "Riwayat Stock Movement dari aktivitas stock yang sudah disubmit.",
  Refresh: "Refresh",
  movements: "Stock Movement",
  "Business date": "Tanggal bisnis",
  "Movement type": "Tipe Stock Movement",
  "All types": "Semua tipe",
  "Search movements": "Cari Stock Movement",
  "Date / Time": "Tanggal / Waktu",
  "Could not load categories.": "Gagal memuat kategori.",
  "Could not update category status.": "Gagal mengubah status kategori.",
  "Could not delete category.": "Gagal menghapus kategori.",
  "Menu Categories": "Kategori HPP",
  "Group menu items by product category.":
    "Kelompokkan menu item berdasarkan kategori produk.",
  "All categories": "Semua kategori",
  "categories found": "kategori ditemukan",
  Used: "Dipakai",
  "Category is used by products": "Kategori sedang dipakai produk",
  "Create category": "Buat kategori",
  "Create this category?": "Buat kategori ini?",
  "Update this category?": "Update kategori ini?",
  "Deactivate category": "Nonaktifkan kategori",
  "Deactivate this category?": "Nonaktifkan kategori ini?",
  Deactivate: "Nonaktifkan",
  "Activate category": "Aktifkan kategori",
  "Activate this category?": "Aktifkan kategori ini?",
  Activate: "Aktifkan",
  "Delete this category permanently?": "Hapus kategori ini permanen?",
  "Category Detail": "Detail Kategori",
  "Products in this category": "Produk dalam kategori ini",
  "Could not load category detail.": "Gagal memuat detail kategori.",
  "Could not update product status.": "Gagal mengubah status produk.",
  "Could not delete product.": "Gagal menghapus produk.",
  "Update this product?": "Update produk ini?",
  "Create this product?": "Buat produk ini?",
  "Deactivate product": "Nonaktifkan produk",
  "Deactivate this product?": "Nonaktifkan produk ini?",
  "Activate product": "Aktifkan produk",
  "Activate this product?": "Aktifkan produk ini?",
  "Delete this product permanently?": "Hapus produk ini permanen?",
  "products found": "produk ditemukan",
  "Product is used by recipes": "Produk sedang dipakai resep",
  "Image URL": "URL Gambar",
  "Could not load menu items.": "Gagal memuat menu item.",
  "View products, recipe versions, and recipe items.":
    "Lihat produk, versi resep, dan item resep.",
  "All menu items": "Semua menu item",
  "menu items found": "menu item ditemukan",
  "Loading menu items...": "Memuat menu item...",
  "No menu items found": "Menu item tidak ditemukan",
  "Could not load product detail.": "Gagal memuat detail produk.",
  "Could not load recipe items.": "Gagal memuat item resep.",
  "Product Detail": "Detail Produk",
  "No category": "Tanpa kategori",
  "Add recipe version": "Tambah versi resep",
  "Recipe Versions": "Versi Resep",
  versions: "versi",
  "No recipe version yet": "Belum ada versi resep",
  "No active recipe": "Belum ada resep aktif",
  Version: "Versi",
  "Active recipe": "Resep aktif",
  "Inactive Versions": "Versi Nonaktif",
  inactive: "nonaktif",
  "Inactive recipe": "Resep nonaktif",
  "Selected recipe version": "Versi resep terpilih",
  "Select recipe version": "Pilih versi resep",
  "Update recipe": "Update resep",
  "Create recipe": "Buat resep",
  "Update this recipe version?": "Update versi resep ini?",
  "Create a new recipe version?": "Buat versi resep baru?",
  "Deactivate recipe": "Nonaktifkan resep",
  "Deactivate this recipe version?": "Nonaktifkan versi resep ini?",
  "Activate recipe": "Aktifkan resep",
  "Activate this recipe version?": "Aktifkan versi resep ini?",
  "Delete recipe": "Hapus resep",
  "Delete this recipe version?": "Hapus versi resep ini?",
  "Update recipe item": "Update item resep",
  "Create recipe item": "Buat item resep",
  "Update this recipe item?": "Update item resep ini?",
  "Create this recipe item?": "Buat item resep ini?",
  "Create item": "Buat item",
  "Delete recipe item": "Hapus item resep",
  "Delete this ingredient from the recipe?": "Hapus bahan ini dari resep?",
  "Base Unit": "Unit Dasar",
  "Enter version": "Masukkan versi",
  "Example: Dine In or Takeaway": "Contoh: Dine In atau Takeaway",
  "Each version has its own ingredients. Add cups and packaging to Takeaway only.": "Setiap versi punya bahan sendiri. Tambahkan cup dan kemasan khusus pada versi Takeaway.",
  "Select ingredient": "Pilih bahan",
  "name is required": "nama wajib diisi",
  "price is required": "harga wajib diisi",
  "version is required": "versi wajib diisi",
  "recipe is required": "resep wajib dipilih",
  "ingredient is required": "bahan wajib dipilih",
  "quantity is required": "qty wajib diisi",
  "Could not update recipe status.": "Gagal mengubah status resep.",
  "Could not load units.": "Gagal memuat satuan isi.",
  "Could not load packaging.": "Gagal memuat satuan kemasan.",
  "Packaging is used by ingredients or prices":
    "Satuan kemasan masih dipakai di Bahan",
  "Manage inventory measurement units.": "Kelola satuan isi stok.",
  "Manage purchase packaging conversions.":
    "Kelola kemasan pembelian dan konversinya ke satuan stok.",
  "Manage purchase packaging units.": "Kelola master satuan kemasan pembelian.",
  "Manage ingredient brand and type variants.":
    "Kelola brand dan varian/type bahan.",
  "Could not load brand types.": "Gagal memuat Brand / Type.",
  "Add brand type": "Tambah Brand / Type",
  "Update brand type": "Update Brand / Type",
  "Create brand type": "Buat Brand / Type",
  "Delete brand type": "Hapus Brand / Type",
  "All brand types": "Semua Brand / Type",
  "brand types found": "Brand / Type ditemukan",
  "Search brand type...": "Cari Brand / Type...",
  "Loading brand types...": "Memuat Brand / Type...",
  "No brand types found": "Brand / Type tidak ditemukan",
  "Create this brand type?": "Buat Brand / Type ini?",
  "Update this brand type?": "Update Brand / Type ini?",
  "Delete this brand type permanently?": "Hapus Brand / Type ini permanen?",
  "Deactivate brand type": "Nonaktifkan Brand / Type",
  "Deactivate this brand type?": "Nonaktifkan Brand / Type ini?",
  "Activate brand type": "Aktifkan Brand / Type",
  "Activate this brand type?": "Aktifkan Brand / Type ini?",
  "Could not update brand type status.": "Gagal mengubah status Brand / Type.",
  "Could not delete brand type.": "Gagal menghapus Brand / Type.",
  "Brand / Type data is ready in the database. CRUD screen is next.":
    "Data Brand / Type sudah siap di database. Layar CRUD menyusul.",
  "Manage supplier prices, packaging content, and effective dates.":
    "Kelola harga supplier, isi kemasan, dan tanggal berlaku.",
  "Master Price & PAR data is ready in the database. CRUD screen is next.":
    "Data Master Harga & PAR sudah siap di database. Layar CRUD menyusul.",
  "All units": "Semua satuan isi",
  "All packaging": "Semua satuan kemasan",
  "units found": "satuan isi ditemukan",
  "packaging found": "satuan kemasan ditemukan",
  Code: "Kode",
  "Unit type": "Tipe satuan isi",
  "all fields are required": "semua field wajib diisi",
  "Create unit": "Buat satuan isi",
  "Create this unit?": "Buat satuan isi ini?",
  "Update this unit?": "Update satuan isi ini?",
  "Delete this unit permanently?": "Hapus satuan isi ini permanen?",
  "Create packaging": "Buat satuan kemasan",
  "Create this packaging?": "Buat satuan kemasan ini?",
  "Update this packaging?": "Update satuan kemasan ini?",
  "Delete this packaging permanently?": "Hapus satuan kemasan ini permanen?",
  "Could not delete unit.": "Gagal menghapus satuan isi.",
  "Could not delete packaging.": "Gagal menghapus satuan kemasan.",
  "Deactivate unit": "Nonaktifkan satuan isi",
  "Deactivate this unit?": "Nonaktifkan satuan isi ini?",
  "Deactivate packaging": "Nonaktifkan satuan kemasan",
  "Deactivate this packaging?": "Nonaktifkan satuan kemasan ini?",
  "Activate unit": "Aktifkan satuan isi",
  "Activate this unit?": "Aktifkan satuan isi ini?",
  "Activate packaging": "Aktifkan satuan kemasan",
  "Activate this packaging?": "Aktifkan satuan kemasan ini?",
  "Could not update unit status.": "Gagal mengubah status satuan isi.",
  "Could not update packaging status.": "Gagal mengubah status satuan kemasan.",
  "Unit is used by ingredients, unit conversions, or stock movements":
    "Satuan isi dipakai oleh bahan, satuan kemasan, atau Stock Movement stok",
  "Could not verify whether this user can be deleted. Please try again.":
    "Belum bisa memeriksa apakah akun dapat dihapus. Silakan coba lagi.",
  "Close the currently open business day first.":
    "Tutup operasional harian yang masih OPEN sebelum membuka yang baru.",
  "close the currently open business day before opening another":
    "Tutup operasional harian yang masih OPEN sebelum membuka yang baru.",
  "Could not verify the open business day. Refresh and try again.":
    "Status operasional harian belum bisa diperiksa. Muat ulang dan coba lagi.",
  "Opening and Closing Stock: Create adds items, Update edits items and notes or submits the count, Delete removes draft items.":
    "Stock Awal dan Akhir: Create menambah item, Update mengubah item dan catatan atau submit opname, Delete menghapus item draft.",
  "Cannot delete user": "Pengguna tidak bisa dihapus",
  "user cannot be deleted because it still has assigned roles":
    "Akun masih memiliki assignment role. Penghapusan diblokir; akun dan assignment role tetap utuh.",
  "user cannot be deleted because operational records reference this account; deactivate the account instead":
    "Akun masih terhubung dengan data operasional. Penghapusan diblokir. Nonaktifkan akun jika sudah tidak digunakan.",
  "Unit is used by ingredients": "Satuan isi sedang dipakai bahan",
  "Could not load ingredients.": "Gagal memuat bahan.",
  "Could not export ingredients.": "Gagal mengekspor bahan.",
  "No changes": "Tidak ada perubahan",
  Skipped: "Dilewati",
  "No ingredient rows to import": "Tidak ada baris bahan untuk diimport.",
  "Could not prepare ingredient import":
    "Tidak dapat membaca file atau memuat data bahan untuk import.",
  "Ingredient updated successfully": "Bahan berhasil diperbarui.",
  "You do not have permission to create ingredients":
    "Anda tidak memiliki izin membuat bahan.",
  "You do not have permission to update ingredients":
    "Anda tidak memiliki izin memperbarui bahan.",
  "Invalid minimum stock": "Stok minimum harus berupa angka nol atau lebih.",
  "Target stock": "Target stok",
  "Invalid target stock": "Target stok harus 0 atau minimal sebesar minimum stok.",
  "Could not export current stock.": "Gagal mengekspor Stok Saat Ini.",
  "Invalid ingredient quantity":
    "Jumlah harus lebih dari nol dan diikuti nama satuan, misalnya 1 Kardus atau 1000 g.",
  "Ambiguous ingredient reference":
    "Nama referensi bahan ambigu. Pastikan nama unik pada kategori dan subkategori yang dipilih.",
  "Unknown ingredient reference":
    "Kategori, subkategori, brand, supplier, atau satuan tidak ditemukan atau tidak aktif.",
  "Invalid ingredient import format":
    "Format import tidak sesuai. Gunakan file export bahan.",
  "Manage stock ingredients and packaging.": "Kelola bahan stok dan kemasan.",
  "Manage stock ingredients and base units.":
    "Kelola bahan stok dan satuan dasar.",
  "All ingredients": "Semua bahan",
  "ingredients found": "bahan ditemukan",
  "Base unit": "Satuan dasar",
  "Content unit": "Satuan isi",
  "Package quantity": "Jumlah kemasan",
  "Content quantity": "Jumlah isi",
  "Could not export packaging.": "Gagal mengekspor satuan kemasan.",
  "Exporting...": "Mengekspor...",
  "Ingredient Categories": "Kategori Bahan",
  "Ingredient Category": "Kategori Bahan",
  "Could not load ingredient categories.": "Gagal memuat kategori bahan.",
  "Update ingredient category": "Ubah kategori bahan",
  "Create ingredient category": "Buat kategori bahan",
  "Update this ingredient category?": "Ubah kategori bahan ini?",
  "Create this ingredient category?": "Buat kategori bahan ini?",
  "Deactivate ingredient category": "Nonaktifkan kategori bahan",
  "Activate ingredient category": "Aktifkan kategori bahan",
  "Deactivate this ingredient category?": "Nonaktifkan kategori bahan ini?",
  "Activate this ingredient category?": "Aktifkan kategori bahan ini?",
  "Could not update ingredient category status.":
    "Gagal mengubah status kategori bahan.",
  "Delete ingredient category": "Hapus kategori bahan",
  "Delete this ingredient category permanently?":
    "Hapus kategori bahan ini permanen?",
  "Could not delete ingredient category.": "Gagal menghapus kategori bahan.",
  "Delete selected ingredient categories": "Hapus kategori bahan terpilih",
  "Delete selected ingredient categories permanently?":
    "Hapus kategori bahan terpilih permanen?",
  "Could not delete selected ingredient categories.":
    "Gagal menghapus kategori bahan terpilih.",
  "Could not export ingredient categories.": "Gagal mengekspor kategori bahan.",
  "Ingredient category name already exists": "Nama kategori bahan sudah ada",
  "Invalid ingredient category input": "Data kategori bahan tidak valid",
  "All ingredient categories": "Semua kategori bahan",
  "ingredient categories found": "kategori bahan ditemukan",
  "Search ingredient category...": "Cari kategori bahan...",
  "Loading ingredient categories...": "Memuat kategori bahan...",
  "No ingredient categories found": "Tidak ada kategori bahan",
  "Select ingredient category": "Pilih kategori bahan",
  "Add ingredient category": "Tambah kategori bahan",
  "Ingredient category is used by ingredients":
    "Kategori bahan dipakai oleh bahan atau brand/type",
  "Manage ingredient categories.": "Kelola kategori bahan.",
  "Name and a valid ingredient category are required":
    "Nama dan kategori bahan yang valid wajib diisi",
  "Packaging unit": "Satuan kemasan",
  "Min stock": "Stock minimum",
  "base unit is required": "satuan dasar wajib dipilih",
  "minimum stock is required": "stock minimum wajib diisi",
  "Create ingredient": "Buat bahan",
  "Create this ingredient?": "Buat bahan ini?",
  "Update this ingredient?": "Update bahan ini?",
  "Delete this ingredient permanently?": "Hapus bahan ini permanen?",
  "Could not delete ingredient.": "Gagal menghapus bahan.",
  "Deactivate ingredient": "Nonaktifkan bahan",
  "Deactivate this ingredient?": "Nonaktifkan bahan ini?",
  "Activate ingredient": "Aktifkan bahan",
  "Activate this ingredient?": "Aktifkan bahan ini?",
  "Could not update ingredient status.": "Gagal mengubah status bahan.",
  "Ingredient is used by ingredient units":
    "Bahan sedang dipakai satuan kemasan",
  "Ingredient Detail": "Detail Bahan",
  "Could not load ingredient detail.": "Gagal memuat detail bahan.",
  "Add unit conversion": "Tambah konversi unit",
  "Unit Conversions": "Satuan kemasan",
  conversions: "konversi",
  Conversion: "Konversi",
  "Loading unit conversions...": "Memuat satuan kemasan...",
  "No unit conversions found": "Satuan kemasan tidak ditemukan",
  "unit is required": "satuan kemasan wajib dipilih",
  "conversion factor is required": "faktor konversi wajib diisi",
  "Update ingredient unit": "Update satuan kemasan",
  "Create ingredient unit": "Buat satuan kemasan",
  "Update this ingredient unit?": "Update satuan kemasan ini?",
  "Create this ingredient unit?": "Buat satuan kemasan ini?",
  "Deactivate ingredient unit": "Nonaktifkan satuan kemasan",
  "Deactivate this ingredient unit?": "Nonaktifkan satuan kemasan ini?",
  "Activate ingredient unit": "Aktifkan satuan kemasan",
  "Activate this ingredient unit?": "Aktifkan satuan kemasan ini?",
  "Could not update ingredient unit status.":
    "Gagal mengubah status satuan kemasan.",
  "Delete ingredient unit": "Hapus satuan kemasan",
  "Delete this ingredient unit permanently?":
    "Hapus satuan kemasan ini permanen?",
  "Could not delete ingredient unit.": "Gagal menghapus satuan kemasan.",
  "Update unit conversion": "Update satuan kemasan",
  "Conversion factor": "Faktor konversi",
  "Minimum stock": "Stock minimum",
  "Select packaging": "Pilih satuan kemasan",
  "Manage supplier contacts and availability.":
    "Kelola kontak dan ketersediaan supplier.",
  "All suppliers": "Semua supplier",
  "suppliers found": "supplier ditemukan",
  "Create supplier": "Buat supplier",
  "Create this supplier?": "Buat supplier ini?",
  "Update this supplier?": "Update supplier ini?",
  "Supplier saved successfully.": "Supplier berhasil disimpan.",
  "Delete this supplier permanently?": "Hapus supplier ini permanen?",
  "Supplier deleted successfully.": "Supplier berhasil dihapus.",
  "Could not delete supplier.": "Gagal menghapus supplier.",
  "Deactivate supplier": "Nonaktifkan supplier",
  "Deactivate this supplier?": "Nonaktifkan supplier ini?",
  "Activate supplier": "Aktifkan supplier",
  "Activate this supplier?": "Aktifkan supplier ini?",
  "Supplier status updated successfully.": "Status supplier berhasil diubah.",
  "Could not update supplier status.": "Gagal mengubah status supplier.",
  "Ingredient Units": "Satuan kemasan",
  "Could not connect to the user service. Please try again.":
    "Gagal terhubung ke layanan user. Coba lagi.",
  "Could not load user roles.": "Gagal memuat role user.",
  "Add roles": "Tambah role",
  "Add the selected roles to this user?":
    "Tambahkan role yang dipilih ke user ini?",
  "Could not add selected roles.": "Gagal menambahkan role yang dipilih.",
  "Remove this role from the user?": "Hapus role ini dari user?",
  "Confirm password must match password":
    "Konfirmasi password harus sama dengan password",
  "Update user": "Update user",
  "Change password": "Ubah password",
  "Deactivate user": "Nonaktifkan user",
  "Activate user": "Aktifkan user",
  "Delete user": "Hapus user",
  "Update this user data?": "Update data user ini?",
  "Change this user password?": "Ubah password user ini?",
  "Deactivate this user account?": "Nonaktifkan akun user ini?",
  "Activate this user account?": "Aktifkan akun user ini?",
  "Delete this user permanently?": "Hapus user ini permanen?",
  "Action failed. Please try again.": "Aksi gagal. Coba lagi.",
  "Manage people who have access to C.R.E.M.A.":
    "Kelola orang yang punya akses ke C.R.E.M.A.",
  "Add user": "Tambah user",
  "All users": "Semua user",
  "registered users": "user terdaftar",
  "Search by name...": "Cari berdasarkan nama...",
  Contact: "Kontak",
  Position: "Posisi",
  "Try another search keyword.": "Coba kata kunci lain.",
  "Manage roles": "Kelola role",
  "Update data": "Update data",
  "Cannot change your own account status":
    "Tidak bisa mengubah status akun sendiri",
  "Cannot delete your own account": "Tidak bisa menghapus akun sendiri",
  "Have user role": "Masih punya role user",
  "Full name": "Nama lengkap",
  "Email address": "Alamat email",
  "Phone number": "Nomor telepon",
  "Current password": "Password saat ini",
  "New password": "Password baru",
  "Confirm password": "Konfirmasi password",
  "User roles": "Role user",
  "Assigned roles": "Role terpasang",
  "This user does not have any roles.": "User ini belum punya role.",
  "Unnamed role": "Role tanpa nama",
  "Delete role from user": "Hapus role dari user",
  "All roles are already assigned.": "Semua role sudah terpasang.",
  "Fullname must be at least 3 characters": "Nama lengkap minimal 3 karakter",
  "Enter a valid email address": "Masukkan alamat email yang valid",
  "Phone is required": "Nomor telepon wajib diisi",
  "Address must be at least 3 characters": "Alamat minimal 3 karakter",
  "Position must be at least 2 characters": "Posisi minimal 2 karakter",
  "Password must be at least 8 characters": "Password minimal 8 karakter",
  "Could not create user. Please try again.": "Gagal membuat user. Coba lagi.",
  "Hide password": "Sembunyikan password",
  "Show password": "Tampilkan password",
  "Add new user": "Tambah user baru",
  "Create an account and provide their workspace details.":
    "Buat akun dan isi detail workspace-nya.",
  Password: "Password",
  "User address": "Alamat user",
  "Minimum 8 characters": "Minimal 8 karakter",
  "Repeat password": "Ulangi password",
  "Creating user...": "Membuat user...",
  "Create user": "Buat user",
  "Create this user account with the details you entered?":
    "Buat akun user ini dengan detail yang sudah diisi?",
  "name must be at least 3 characters": "nama minimal 3 karakter",
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const value = useMemo<LanguageContextValue>(
    () => ({
      language: "id",
      t: (text) => translations[text] ?? text,
    }),
    [],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
