import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Language = "id" | "en";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (text: string) => string;
};

const STORAGE_KEY = "crema-language";

const translations: Record<string, string> = {
  "Open navigation": "Buka navigasi",
  Notifications: "Notifikasi",
  "Open account menu": "Buka menu akun",
  Profile: "Profil",
  Logout: "Keluar",
  "Close profile": "Tutup profil",
  "Team Member": "Anggota Tim",
  Email: "Email",
  Phone: "Telepon",
  "Confirm logout?": "Konfirmasi keluar?",
  "You’ll need to sign in again to access the C.R.E.M.A dashboard.":
    "Kamu perlu masuk lagi untuk mengakses dashboard C.R.E.M.A.",
  Cancel: "Batal",
  "Logging out...": "Sedang keluar...",
  "Close menu": "Tutup menu",
  "Search sidebar menus": "Cari menu sidebar",
  "Search menus": "Cari menu",
  "Search menus...": "Cari menu...",
  "Clear menu search": "Bersihkan pencarian menu",
  "Main navigation": "Navigasi utama",
  Overview: "Ringkasan",
  "Business Days": "Bisnis Harian",
  "User Management": "Manajemen User",
  "Role Management": "Manajemen Role",
  "Unit Management": "Manajemen Unit",
  "Ingredient Management": "Manajemen Bahan",
  Suppliers: "Supplier",
  "Stock Count": "Stock Opname",
  "Stock In": "Stock Masuk",
  "Stock Adjustments": "Penyesuaian Stock",
  "Stock Movements": "Mutasi Stock",
  "Menu Items": "Menu Item",
  Dashboard: "Dashboard",
  Users: "User",
  Roles: "Role",
  Units: "Unit",
  Ingredients: "Bahan",
  Categories: "Kategori",
  Products: "Produk",
  Recipes: "Resep",
  "Recipe Items": "Item Resep",
  Inventory: "Inventori",
  Menu: "Menu",
  "Master Data": "Data Master",
  "No menus found": "Menu tidak ditemukan",
  "Try another keyword.": "Coba kata kunci lain.",
  "Manage access roles and review assigned users.":
    "Kelola role akses dan cek user yang terhubung.",
  "Add role": "Tambah role",
  "Create role": "Buat role",
  "Create this role?": "Buat role ini?",
  "Update this role name?": "Update nama role ini?",
  "All roles": "Semua role",
  "roles found": "role ditemukan",
  "Search role...": "Cari role...",
  Role: "Role",
  Usage: "Pemakaian",
  Action: "Aksi",
  "Loading roles...": "Memuat role...",
  "No roles found": "Role tidak ditemukan",
  Assigned: "Terpasang",
  Unused: "Belum dipakai",
  "Manage users": "Kelola user",
  "Update role": "Update role",
  "Have assigned users": "Masih punya user",
  "Delete role": "Hapus role",
  "Delete this role permanently?": "Hapus role ini permanen?",
  "Confirm": "Konfirmasi",
  Page: "Halaman",
  of: "dari",
  Limit: "Limit",
  Previous: "Sebelumnya",
  Next: "Berikutnya",
  "Only Admin and HRIS Admin can access this page.":
    "Hanya Admin dan HRIS Admin yang bisa mengakses halaman ini.",
  "Create a new access role.": "Buat role akses baru.",
  "Role name": "Nama role",
  "Menu permissions": "Permission menu",
  "menus selected": "menu dipilih",
  Read: "Lihat",
  Create: "Tambah",
  Update: "Ubah",
  Delete: "Hapus",
  All: "Semua",
  "Read is required by enabled permissions":
    "Read wajib aktif karena permission lain menyala",
  "Saving...": "Menyimpan...",
  Save: "Simpan",
  "Assigned users": "User terpasang",
  "Loading users...": "Memuat user...",
  "This role is not assigned to any users.":
    "Role ini belum dipasang ke user mana pun.",
  "Unnamed user": "User tanpa nama",
  "You cannot remove your own admin role":
    "Kamu tidak bisa menghapus role admin milik sendiri",
  "Remove user from role": "Hapus user dari role",
  "Only admin can change admin role assignments":
    "Hanya admin yang bisa mengubah pemasangan role admin",
  "Add users": "Tambah user",
  "Assign the selected users to this role?":
    "Pasang user yang dipilih ke role ini?",
  "All users are already assigned.": "Semua user sudah terpasang.",
  "Add selected": "Tambah yang dipilih",
  "Remove user": "Hapus user",
  "Remove this user from the role?": "Hapus user ini dari role?",
  Close: "Tutup",
  "Could not load roles.": "Gagal memuat role.",
  "Action failed.": "Aksi gagal.",
  "Could not delete role.": "Gagal menghapus role.",
  "Could not load assigned users.": "Gagal memuat user terpasang.",
  "Could not assign selected users.": "Gagal memasang user yang dipilih.",
  "Could not remove user from role.": "Gagal menghapus user dari role.",
  "No items yet": "Belum ada item",
  "Loading items...": "Memuat item...",
  "Loading products...": "Memuat produk...",
  "Loading recipes...": "Memuat resep...",
  "Loading suppliers...": "Memuat supplier...",
  "Loading ingredients...": "Memuat bahan...",
  "Loading units...": "Memuat unit...",
  "Loading stock counts...": "Memuat stock opname...",
  "Loading stock receipts...": "Memuat stock masuk...",
  "Loading stock adjustments...": "Memuat penyesuaian stock...",
  "Loading movements...": "Memuat mutasi...",
  "No movements found. Submit Stock In with items to record incoming quantities.":
    "Mutasi belum ditemukan. Submit Stock Masuk berisi item untuk mencatat qty masuk.",
  "No items found": "Item tidak ditemukan",
  "No users found": "User tidak ditemukan",
  "No products found": "Produk tidak ditemukan",
  "No categories found": "Kategori tidak ditemukan",
  "No ingredients found": "Bahan tidak ditemukan",
  "No suppliers found": "Supplier tidak ditemukan",
  "No units found": "Unit tidak ditemukan",
  "Search adjustment...": "Cari penyesuaian...",
  "Search receipt...": "Cari penerimaan...",
  "Search ingredient...": "Cari bahan...",
  "Search supplier...": "Cari supplier...",
  "Search unit...": "Cari unit...",
  "Search category...": "Cari kategori...",
  "Search product...": "Cari produk...",
  "Search menu item...": "Cari menu item...",
  "Ingredient or reference...": "Bahan atau referensi...",
  "Add item": "Tambah item",
  "Update item": "Update item",
  "Delete item": "Hapus item",
  "Add product": "Tambah produk",
  "Update product": "Update produk",
  "Delete product": "Hapus produk",
  "Add category": "Tambah kategori",
  "Update category": "Update kategori",
  "Delete category": "Hapus kategori",
  "Add ingredient": "Tambah bahan",
  "Update ingredient": "Update bahan",
  "Delete ingredient": "Hapus bahan",
  "Add supplier": "Tambah supplier",
  "Update supplier": "Update supplier",
  "Delete supplier": "Hapus supplier",
  "Add unit": "Tambah unit",
  "Update unit": "Update unit",
  "Delete unit": "Hapus unit",
  Name: "Nama",
  Description: "Deskripsi",
  Status: "Status",
  Active: "Aktif",
  Inactive: "Nonaktif",
  Price: "Harga",
  Quantity: "Qty",
  Type: "Tipe",
  Reason: "Alasan",
  Date: "Tanggal",
  Notes: "Catatan",
  Product: "Produk",
  Category: "Kategori",
  Ingredient: "Bahan",
  Supplier: "Supplier",
  Unit: "Unit",
  "Business day": "Bisnis harian",
  "Created by": "Dibuat oleh",
  "Submitted by": "Disubmit oleh",
  "Open Stock In": "Buka Stock Masuk",
  "Select supplier": "Pilih supplier",
  "Could not load suppliers": "Gagal memuat supplier",
  "Could not load suppliers.": "Gagal memuat supplier.",
  "Name is required": "Nama wajib diisi",
  "Good morning": "Selamat pagi",
  "Good afternoon": "Selamat siang",
  "Good evening": "Selamat sore",
  "Good night": "Selamat malam",
  User: "User",
  "Here’s what’s happening at your coffee shop today.":
    "Ini ringkasan aktivitas kedai kopi kamu hari ini.",
  "+ New order": "+ Pesanan baru",
  "Today’s revenue": "Pendapatan hari ini",
  "Total orders": "Total pesanan",
  "Active products": "Produk aktif",
  "New customers": "Pelanggan baru",
  "4 low stock": "4 stock menipis",
  "Revenue overview": "Ringkasan pendapatan",
  "Performance over the last 7 days": "Performa 7 hari terakhir",
  "Recent orders": "Pesanan terbaru",
  "Latest store activity": "Aktivitas toko terbaru",
  Paid: "Lunas",
  Mon: "Sen",
  Tue: "Sel",
  Wed: "Rab",
  Thu: "Kam",
  Fri: "Jum",
  Sat: "Sab",
  Sun: "Min",
  "Track operational dates for daily, monthly, and yearly reports.":
    "Kelola operasional harian untuk laporan harian, bulanan, dan tahunan.",
  "Business day already exists": "Operasional harian sudah ada",
  "Open business day": "Buka operasional harian",
  "Operational Days": "Operasional Harian",
  "business days found": "operasional harian ditemukan",
  "All status": "Semua status",
  Open: "Buka",
  Closed: "Tutup",
  "Opened By": "Dibuka Oleh",
  "Opened At": "Dibuka Pada",
  "Closed By": "Ditutup Oleh",
  "Closed At": "Ditutup Pada",
  "Loading business days...": "Memuat operasional harian...",
  "No business days found": "Operasional harian tidak ditemukan",
  "Submit all draft Stock In first": "Submit semua draft Stock Masuk dulu",
  "Submit all draft Stock Adjustment first":
    "Submit semua draft Penyesuaian Stock dulu",
  "Close business day": "Tutup operasional harian",
  "Submit closing stock first": "Submit closing stock dulu",
  "Delete stock count first": "Hapus stock opname dulu",
  "Open day": "Buka operasional",
  "Close day": "Tutup operasional",
  "Delete day": "Hapus operasional",
  "Open business day for": "Buka operasional harian untuk",
  "Close business day for": "Tutup operasional harian untuk",
  "Delete business day for": "Hapus operasional harian untuk",
  "This is only allowed when it has no operational records.":
    "Ini hanya bisa dilakukan kalau belum ada catatan operasional.",
  "Could not load business days.": "Gagal memuat operasional harian.",
  "Could not open business day.": "Gagal membuka operasional harian.",
  "Could not close business day.": "Gagal menutup operasional harian.",
  "Could not delete business day.": "Gagal menghapus operasional harian.",
  "Could not load inventory counts.": "Gagal memuat stock opname.",
  "Opening Stock": "Stock Awal",
  "Closing Stock": "Stock Akhir",
  "Physical stock before operational activities": "Stock fisik sebelum operasional dimulai",
  "Physical stock after operational activities": "Stock fisik setelah operasional selesai",
  "Waiting for stock count": "Menunggu stock opname",
  "Submit opening stock": "Submit stock awal",
  "View closing stock": "Lihat stock akhir",
  "Review stock movement": "Cek mutasi stock",
  Done: "Selesai",
  Draft: "Draft",
  "Counted by": "Dihitung oleh",
  Submitted: "Disubmit",
  View: "Lihat",
  Today: "Hari ini",
  "Daily workflow": "Alur harian",
  "Stock count complete": "Stock opname selesai",
  "Continue daily inventory": "Lanjutkan inventori harian",
  "Start with Opening Stock": "Mulai dari Stock Awal",
  "Opening and Closing Stock have been submitted.":
    "Stock Awal dan Stock Akhir sudah disubmit.",
  "Record Stock In or Adjustment when needed. If there is none, continue to Closing Stock.":
    "Catat Stock Masuk atau Penyesuaian jika perlu. Kalau tidak ada, lanjut ke Stock Akhir.",
  "Count physical stock before operational activities begin.":
    "Hitung stock fisik sebelum operasional dimulai.",
  "Count beginning stock.": "Hitung stock awal.",
  "Not submitted": "Belum disubmit",
  "Use only when goods arrive.": "Gunakan hanya saat barang datang.",
  Optional: "Opsional",
  Adjustment: "Penyesuaian",
  "Correct stock when needed.": "Koreksi stock jika diperlukan.",
  Movement: "Mutasi",
  "Review the ledger.": "Cek kartu stock.",
  Review: "Cek",
  "Count ending stock.": "Hitung stock akhir.",
  "Stock count tasks": "Task stock opname",
  "Opening and closing counts for this business day.":
    "Hitung stock awal dan akhir untuk operasional harian ini.",
  "No stock counts found for this date": "Stock opname untuk tanggal ini tidak ditemukan",
  "No business day found for this date":
    "Bisnis harian untuk tanggal ini belum dibuat",
  "Could not load stock receipts.": "Gagal memuat stock masuk.",
  "Please select a supplier.": "Pilih supplier dulu.",
  "Open a business day and submit Opening Stock before creating stock in.":
    "Buka operasional harian dan submit Stock Awal sebelum membuat Stock Masuk.",
  "Save stock in draft": "Simpan draft Stock Masuk",
  "Save this stock in as a draft? You can add items and submit it from the detail page.":
    "Simpan Stock Masuk ini sebagai draft? Item bisa ditambahkan dan disubmit dari halaman detail.",
  "Save Draft": "Simpan Draft",
  "Draft saved successfully.": "Draft berhasil disimpan.",
  "Delete stock in": "Hapus Stock Masuk",
  "Delete this empty stock in record?": "Hapus data Stock Masuk kosong ini?",
  "Could not delete stock receipt.": "Gagal menghapus Stock Masuk.",
  "Track incoming inventory receipts and received items.":
    "Catat barang masuk dan item yang diterima.",
  "Open a business day first": "Buka operasional harian dulu",
  "Submit Opening Stock first": "Submit Stock Awal dulu",
  "Add stock in": "Tambah Stock Masuk",
  "Stock Receipts": "Data Stock Masuk",
  "records found": "data ditemukan",
  "Stock in can only be added when this business day is open.":
    "Stock Masuk hanya bisa ditambah saat operasional harian ini masih buka.",
  "Open a business day before adding stock in.":
    "Buka operasional harian sebelum menambah Stock Masuk.",
  "Submit Opening Stock before adding or changing stock in.":
    "Submit Stock Awal sebelum menambah atau mengubah Stock Masuk.",
  Receipt: "Penerimaan",
  "Created At": "Dibuat Pada",
  "No stock receipts yet": "Belum ada Stock Masuk",
  "Remove all items before deleting this stock in":
    "Hapus semua item sebelum menghapus Stock Masuk ini",
  "Business Date": "Tanggal Bisnis",
  "Auto from current open business day":
    "Otomatis dari operasional harian yang sedang buka",
  "Supplier *": "Supplier *",
  "Example: delivery received complete, invoice checked.":
    "Contoh: barang diterima lengkap, invoice sudah dicek.",
  "Could not load stock adjustments.": "Gagal memuat penyesuaian stock.",
  "Reason is required.": "Alasan wajib diisi.",
  "Open a business day and submit Opening Stock before creating stock adjustment.":
    "Buka operasional harian dan submit Stock Awal sebelum membuat Penyesuaian Stock.",
  "Save stock adjustment draft": "Simpan draft Penyesuaian Stock",
  "Save this stock adjustment as a draft?": "Simpan Penyesuaian Stock ini sebagai draft?",
  "Delete stock adjustment": "Hapus Penyesuaian Stock",
  "Delete this empty stock adjustment record?":
    "Hapus data Penyesuaian Stock kosong ini?",
  "Could not delete stock adjustment.": "Gagal menghapus Penyesuaian Stock.",
  "Stock Adjustment": "Penyesuaian Stock",
  "Record approved inventory corrections.": "Catat koreksi stock yang sudah disetujui.",
  "Add adjustment": "Tambah Penyesuaian",
  "Stock adjustment can only be added when this business day is open.":
    "Penyesuaian Stock hanya bisa ditambah saat operasional harian ini masih buka.",
  "Open a business day before adding stock adjustment.":
    "Buka operasional harian sebelum menambah Penyesuaian Stock.",
  "Submit Opening Stock before adding or changing stock adjustment.":
    "Submit Stock Awal sebelum menambah atau mengubah Penyesuaian Stock.",
  "No stock adjustments yet": "Belum ada Penyesuaian Stock",
  "Remove all items before deleting this adjustment":
    "Hapus semua item sebelum menghapus penyesuaian ini",
  "Add stock adjustment": "Tambah Penyesuaian Stock",
  "Reason *": "Alasan *",
  "Could not load stock movements.": "Gagal memuat mutasi stock.",
  "Order Usage": "Pemakaian Order",
  Waste: "Waste",
  "Inventory quantity changes": "Perubahan jumlah inventori",
  "Stock Movement": "Mutasi Stock",
  "Submitted Stock In is recorded automatically in each ingredient’s base unit.":
    "Stock Masuk yang sudah disubmit otomatis tercatat dalam unit dasar tiap bahan.",
  Refresh: "Refresh",
  movements: "mutasi",
  "Business date": "Tanggal bisnis",
  "Movement type": "Tipe mutasi",
  "All types": "Semua tipe",
  "Search movements": "Cari mutasi",
  "Date / Time": "Tanggal / Waktu",
  "Could not load categories.": "Gagal memuat kategori.",
  "Could not update category status.": "Gagal mengubah status kategori.",
  "Could not delete category.": "Gagal menghapus kategori.",
  "Menu Categories": "Kategori Menu",
  "Group menu items by product category.": "Kelompokkan menu item berdasarkan kategori produk.",
  "All categories": "Semua kategori",
  "categories found": "kategori ditemukan",
  Used: "Dipakai",
  "Category is used by products": "Kategori sedang dipakai produk",
  "Create category": "Buat kategori",
  "Create this category?": "Buat kategori ini?",
  "Update this category?": "Update kategori ini?",
  "Deactivate category": "Nonaktifkan kategori",
  "Deactivate this category?": "Nonaktifkan kategori ini?",
  Deactivate: "Nonaktifkan",
  "Activate category": "Aktifkan kategori",
  "Activate this category?": "Aktifkan kategori ini?",
  Activate: "Aktifkan",
  "Delete this category permanently?": "Hapus kategori ini permanen?",
  "Category Detail": "Detail Kategori",
  "Products in this category": "Produk dalam kategori ini",
  "Could not load category detail.": "Gagal memuat detail kategori.",
  "Could not update product status.": "Gagal mengubah status produk.",
  "Could not delete product.": "Gagal menghapus produk.",
  "Update this product?": "Update produk ini?",
  "Create this product?": "Buat produk ini?",
  "Deactivate product": "Nonaktifkan produk",
  "Deactivate this product?": "Nonaktifkan produk ini?",
  "Activate product": "Aktifkan produk",
  "Activate this product?": "Aktifkan produk ini?",
  "Delete this product permanently?": "Hapus produk ini permanen?",
  "products found": "produk ditemukan",
  "Product is used by recipes": "Produk sedang dipakai resep",
  "Image URL": "URL Gambar",
  "Could not load menu items.": "Gagal memuat menu item.",
  "View products, recipe versions, and recipe items.":
    "Lihat produk, versi resep, dan item resep.",
  "All menu items": "Semua menu item",
  "menu items found": "menu item ditemukan",
  "Loading menu items...": "Memuat menu item...",
  "No menu items found": "Menu item tidak ditemukan",
  "Could not load product detail.": "Gagal memuat detail produk.",
  "Could not load recipe items.": "Gagal memuat item resep.",
  "Product Detail": "Detail Produk",
  "No category": "Tanpa kategori",
  "Add recipe version": "Tambah versi resep",
  "Recipe Versions": "Versi Resep",
  versions: "versi",
  "No recipe version yet": "Belum ada versi resep",
  "No active recipe": "Belum ada resep aktif",
  Version: "Versi",
  "Active recipe": "Resep aktif",
  "Inactive Versions": "Versi Nonaktif",
  inactive: "nonaktif",
  "Inactive recipe": "Resep nonaktif",
  "Selected recipe version": "Versi resep terpilih",
  "Select recipe version": "Pilih versi resep",
  "Update recipe": "Update resep",
  "Create recipe": "Buat resep",
  "Update this recipe version?": "Update versi resep ini?",
  "Create a new recipe version?": "Buat versi resep baru?",
  "Deactivate recipe": "Nonaktifkan resep",
  "Deactivate this recipe version?": "Nonaktifkan versi resep ini?",
  "Activate recipe": "Aktifkan resep",
  "Activate this recipe version?": "Aktifkan versi resep ini?",
  "Delete recipe": "Hapus resep",
  "Delete this recipe version?": "Hapus versi resep ini?",
  "Update recipe item": "Update item resep",
  "Create recipe item": "Buat item resep",
  "Update this recipe item?": "Update item resep ini?",
  "Create this recipe item?": "Buat item resep ini?",
  "Create item": "Buat item",
  "Delete recipe item": "Hapus item resep",
  "Delete this ingredient from the recipe?": "Hapus bahan ini dari resep?",
  "Base Unit": "Unit Dasar",
  "Enter version": "Masukkan versi",
  "Select ingredient": "Pilih bahan",
  "name is required": "nama wajib diisi",
  "price is required": "harga wajib diisi",
  "version is required": "versi wajib diisi",
  "recipe is required": "resep wajib dipilih",
  "ingredient is required": "bahan wajib dipilih",
  "quantity is required": "qty wajib diisi",
  "Could not update recipe status.": "Gagal mengubah status resep.",
  "Could not load units.": "Gagal memuat unit.",
  "Manage inventory measurement units.": "Kelola satuan ukur inventori.",
  "All units": "Semua unit",
  "units found": "unit ditemukan",
  Code: "Kode",
  "Unit type": "Tipe unit",
  "all fields are required": "semua field wajib diisi",
  "Create unit": "Buat unit",
  "Create this unit?": "Buat unit ini?",
  "Update this unit?": "Update unit ini?",
  "Delete this unit permanently?": "Hapus unit ini permanen?",
  "Could not delete unit.": "Gagal menghapus unit.",
  "Deactivate unit": "Nonaktifkan unit",
  "Deactivate this unit?": "Nonaktifkan unit ini?",
  "Activate unit": "Aktifkan unit",
  "Activate this unit?": "Aktifkan unit ini?",
  "Could not update unit status.": "Gagal mengubah status unit.",
  "Unit is used by ingredients": "Unit sedang dipakai bahan",
  "Could not load ingredients.": "Gagal memuat bahan.",
  "Manage stock ingredients and base units.": "Kelola bahan stock dan unit dasar.",
  "All ingredients": "Semua bahan",
  "ingredients found": "bahan ditemukan",
  "Base unit": "Unit dasar",
  "Min stock": "Stock minimum",
  "base unit is required": "unit dasar wajib dipilih",
  "minimum stock is required": "stock minimum wajib diisi",
  "Create ingredient": "Buat bahan",
  "Create this ingredient?": "Buat bahan ini?",
  "Update this ingredient?": "Update bahan ini?",
  "Delete this ingredient permanently?": "Hapus bahan ini permanen?",
  "Could not delete ingredient.": "Gagal menghapus bahan.",
  "Deactivate ingredient": "Nonaktifkan bahan",
  "Deactivate this ingredient?": "Nonaktifkan bahan ini?",
  "Activate ingredient": "Aktifkan bahan",
  "Activate this ingredient?": "Aktifkan bahan ini?",
  "Could not update ingredient status.": "Gagal mengubah status bahan.",
  "Ingredient is used by ingredient units": "Bahan sedang dipakai konversi unit",
  "Ingredient Detail": "Detail Bahan",
  "Could not load ingredient detail.": "Gagal memuat detail bahan.",
  "Add unit conversion": "Tambah konversi unit",
  "Unit Conversions": "Konversi Unit",
  conversions: "konversi",
  Conversion: "Konversi",
  "Loading unit conversions...": "Memuat konversi unit...",
  "No unit conversions found": "Konversi unit tidak ditemukan",
  "unit is required": "unit wajib dipilih",
  "conversion factor is required": "faktor konversi wajib diisi",
  "Update ingredient unit": "Update konversi unit",
  "Create ingredient unit": "Buat konversi unit",
  "Update this ingredient unit?": "Update konversi unit ini?",
  "Create this ingredient unit?": "Buat konversi unit ini?",
  "Deactivate ingredient unit": "Nonaktifkan konversi unit",
  "Deactivate this ingredient unit?": "Nonaktifkan konversi unit ini?",
  "Activate ingredient unit": "Aktifkan konversi unit",
  "Activate this ingredient unit?": "Aktifkan konversi unit ini?",
  "Could not update ingredient unit status.":
    "Gagal mengubah status konversi unit.",
  "Delete ingredient unit": "Hapus konversi unit",
  "Delete this ingredient unit permanently?":
    "Hapus konversi unit ini permanen?",
  "Could not delete ingredient unit.": "Gagal menghapus konversi unit.",
  "Update unit conversion": "Update konversi unit",
  "Conversion factor": "Faktor konversi",
  "Minimum stock": "Stock minimum",
  "Select unit": "Pilih unit",
  "Manage supplier contacts and availability.":
    "Kelola kontak dan ketersediaan supplier.",
  "All suppliers": "Semua supplier",
  "suppliers found": "supplier ditemukan",
  "Create supplier": "Buat supplier",
  "Create this supplier?": "Buat supplier ini?",
  "Update this supplier?": "Update supplier ini?",
  "Supplier saved successfully.": "Supplier berhasil disimpan.",
  "Delete this supplier permanently?": "Hapus supplier ini permanen?",
  "Supplier deleted successfully.": "Supplier berhasil dihapus.",
  "Could not delete supplier.": "Gagal menghapus supplier.",
  "Deactivate supplier": "Nonaktifkan supplier",
  "Deactivate this supplier?": "Nonaktifkan supplier ini?",
  "Activate supplier": "Aktifkan supplier",
  "Activate this supplier?": "Aktifkan supplier ini?",
  "Supplier status updated successfully.":
    "Status supplier berhasil diubah.",
  "Could not update supplier status.": "Gagal mengubah status supplier.",
  "Ingredient Units": "Konversi Unit Bahan",
  "Could not connect to the user service. Please try again.":
    "Gagal terhubung ke layanan user. Coba lagi.",
  "Could not load user roles.": "Gagal memuat role user.",
  "Add roles": "Tambah role",
  "Add the selected roles to this user?":
    "Tambahkan role yang dipilih ke user ini?",
  "Could not add selected roles.": "Gagal menambahkan role yang dipilih.",
  "Remove this role from the user?": "Hapus role ini dari user?",
  "Confirm password must match password":
    "Konfirmasi password harus sama dengan password",
  "Update user": "Update user",
  "Change password": "Ubah password",
  "Deactivate user": "Nonaktifkan user",
  "Activate user": "Aktifkan user",
  "Delete user": "Hapus user",
  "Update this user data?": "Update data user ini?",
  "Change this user password?": "Ubah password user ini?",
  "Deactivate this user account?": "Nonaktifkan akun user ini?",
  "Activate this user account?": "Aktifkan akun user ini?",
  "Delete this user permanently?": "Hapus user ini permanen?",
  "Action failed. Please try again.": "Aksi gagal. Coba lagi.",
  "Manage people who have access to C.R.E.M.A.":
    "Kelola orang yang punya akses ke C.R.E.M.A.",
  "Add user": "Tambah user",
  "All users": "Semua user",
  "registered users": "user terdaftar",
  "Search by name...": "Cari berdasarkan nama...",
  Contact: "Kontak",
  Position: "Posisi",
  "Try another search keyword.": "Coba kata kunci lain.",
  "Manage roles": "Kelola role",
  "Update data": "Update data",
  "Cannot change your own account status":
    "Tidak bisa mengubah status akun sendiri",
  "Cannot delete your own account": "Tidak bisa menghapus akun sendiri",
  "Have user role": "Masih punya role user",
  "Full name": "Nama lengkap",
  "Email address": "Alamat email",
  "Phone number": "Nomor telepon",
  "Current password": "Password saat ini",
  "New password": "Password baru",
  "Confirm password": "Konfirmasi password",
  "User roles": "Role user",
  "Assigned roles": "Role terpasang",
  "This user does not have any roles.": "User ini belum punya role.",
  "Unnamed role": "Role tanpa nama",
  "Delete role from user": "Hapus role dari user",
  "All roles are already assigned.": "Semua role sudah terpasang.",
  "Fullname must be at least 3 characters":
    "Nama lengkap minimal 3 karakter",
  "Enter a valid email address": "Masukkan alamat email yang valid",
  "Phone is required": "Nomor telepon wajib diisi",
  "Address must be at least 3 characters": "Alamat minimal 3 karakter",
  "Position must be at least 2 characters": "Posisi minimal 2 karakter",
  "Password must be at least 8 characters":
    "Password minimal 8 karakter",
  "Could not create user. Please try again.":
    "Gagal membuat user. Coba lagi.",
  "Hide password": "Sembunyikan password",
  "Show password": "Tampilkan password",
  "Add new user": "Tambah user baru",
  "Create an account and provide their workspace details.":
    "Buat akun dan isi detail workspace-nya.",
  Password: "Password",
  "User address": "Alamat user",
  "Minimum 8 characters": "Minimal 8 karakter",
  "Repeat password": "Ulangi password",
  "Creating user...": "Membuat user...",
  "Create user": "Buat user",
  "Create this user account with the details you entered?":
    "Buat akun user ini dengan detail yang sudah diisi?",
  "name must be at least 3 characters": "nama minimal 3 karakter",
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function getInitialLanguage(): Language {
  if (typeof window === "undefined") return "id";
  return window.localStorage.getItem(STORAGE_KEY) === "en" ? "en" : "id";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage: setLanguageState,
      t: (text) => (language === "id" ? translations[text] ?? text : text),
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

export function translateStaticText(language: Language, text: string) {
  if (language === "en") return text;
  return translations[text] ?? text;
}
