import { exportSellingPrices } from "../../utils/sellingPriceReport";
import { useEffect, useRef, useState } from "react";
import { isAxiosError } from "axios";
import { Calculator, Save, Plus, X, Eye, Pencil, Trash2, Power, Download } from "lucide-react";
import ConfirmDialog from "../../components/common/ConfirmDialog";
import Navbar from "../../components/layout/Navbar";
import Sidebar from "../../components/layout/Sidebar";
import { useAuth } from "../../app/AuthContext";
import { userCan } from "../../app/roleAccess";
import { getSellingSources,getSellingCost,getSellingHistory,createSellingSnapshot,updateSellingSnapshot,deleteSellingSnapshot,setSellingSnapshotActive,type SellingSource,type SellingRow,type SellingCalculation } from "../../api/sellingPrice.api";
import type { RecipeCost } from "../../api/recipe.api";
const labels=["Overhead","Variable","Meal Allowance","Capital Ex","Labour","Rent Ex","Margin"];
const money=(value:string|number)=>`Rp ${new Intl.NumberFormat("id-ID",{maximumFractionDigits:0}).format(Number(value))}`;
const message=(e:unknown)=>isAxiosError<{message?:string}>(e)?e.response?.data?.message||"Gagal memuat data.":"Gagal memuat data.";
const currentMonth=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).format(new Date());
function Breakdown({data}:{data:SellingCalculation}) {
 return <table className="w-full text-sm"><thead className="bg-[var(--color-brand-primary)] text-white"><tr><th className="p-3 text-left">Komponen</th><th className="p-3 text-right">Persen</th><th className="p-3 text-right">Sub HPP</th></tr></thead><tbody><tr className="border-b"><td className="p-3">HPP resep</td><td/><td className="p-3 text-right">{money(data.base_hpp)}</td></tr>{data.components.map(c=><tr key={c.label} className="border-b"><td className="p-3">{c.label}</td><td className="p-3 text-right">{Number(c.percent)}%</td><td className="p-3 text-right">{money(c.amount)}</td></tr>)}{[["Total HPP",data.total_hpp],["Harga jual",data.selling_price],["Surplus",data.surplus]].map(([label,value])=><tr key={label} className={`border-b font-bold ${label==="Surplus"?Number(value)<0?"bg-red-50 text-red-700":"bg-green-50 text-green-800":""}`}><td className="p-3" colSpan={2}>{label}</td><td className="p-3 text-right">{money(value)}</td></tr>)}</tbody></table>;
}
export default function SellingPriceHPPPage(){
 const {user}=useAuth();const canCreate=userCan(user,"selling_price_hpp","create");
 const [exporting,setExporting]=useState(false);
 const [statusTarget,setStatusTarget]=useState<SellingRow|null>(null);
 const [editing,setEditing]=useState<SellingRow|null>(null);const [deleting,setDeleting]=useState<SellingRow|null>(null);
 const canEdit=userCan(user,"selling_price_hpp","update");const canDelete=userCan(user,"selling_price_hpp","delete");
 const detailDialog=useRef<HTMLDialogElement>(null);
 const [showForm,setShowForm]=useState(false);
 const [sidebar,setSidebar]=useState(false);const [period,setPeriod]=useState(currentMonth);const [sources,setSources]=useState<SellingSource[]>([]);const [recipe,setRecipe]=useState("");
 const [percents,setPercents]=useState(labels.map(()=>"0"));const [price,setPrice]=useState("");const [cost,setCost]=useState<RecipeCost|null>(null);const [history,setHistory]=useState<SellingRow[]>([]);const [selected,setSelected]=useState<SellingRow|null>(null);
 const [error,setError]=useState("");const [notice,setNotice]=useState("");const [saving,setSaving]=useState(false);const [loadingCost,setLoadingCost]=useState(false);const [loadingHistory,setLoadingHistory]=useState(false);const [page,setPage]=useState(0);const [total,setTotal]=useState(0);const [refresh,setRefresh]=useState(0);const [requestID,setRequestID]=useState(()=>crypto.randomUUID());
 useEffect(()=>{
  const dialog=detailDialog.current;
  if(!selected||!dialog)return;
  const previousOverflow=document.body.style.overflow;
  document.body.style.overflow="hidden";
  dialog.showModal();
  return()=>{dialog.close();document.body.style.overflow=previousOverflow};
 },[selected]);
 const input="w-full rounded-xl border border-stone-300 bg-white p-3 disabled:bg-stone-100";
 useEffect(()=>{let active=true;getSellingSources().then(r=>{if(active)setSources(r.data||[])}).catch(e=>{if(active)setError(message(e))});return()=>{active=false}},[]);
 useEffect(()=>{setPage(0);setSelected(null);setEditing(null);setShowForm(false)},[period]);
 useEffect(()=>{let active=true;setLoadingHistory(true);getSellingHistory(period,page*50).then(r=>{if(active){setHistory(r.data||[]);setTotal(r.total||0)}}).catch(e=>{if(active){setHistory([]);setError(message(e))}}).finally(()=>{if(active)setLoadingHistory(false)});return()=>{active=false}},[period,page,refresh]);
 useEffect(()=>{let active=true;if(editing){setCost(editing.snapshot.recipe_cost);setLoadingCost(false);return;}setCost(null);if(!recipe)return;setLoadingCost(true);getSellingCost(recipe).then(r=>{if(active)setCost(r.data)}).catch(e=>{if(active)setError(message(e))}).finally(()=>{if(active)setLoadingCost(false)});return()=>{active=false}},[recipe,refresh,editing]);
 const valid=!!cost?.complete&&cost.total_cost!==null&&price.trim()!==""&&Number.isFinite(Number(price))&&Number(price)>=0&&percents.every(p=>p.trim()!==""&&Number.isFinite(Number(p))&&Number(p)>=0&&Number(p)<=100);
 const base=Number(cost?.total_cost||0);const components=labels.map((label,i)=>({label,percent:percents[i],amount:String(base*Number(percents[i])/100)}));const totalHPP=base+components.reduce((s,c)=>s+Number(c.amount),0);
 const preview:SellingCalculation={base_hpp:String(base),components,total_hpp:String(totalHPP),selling_price:price,surplus:String(Number(price)-totalHPP)};
 async function save(){if(!valid||saving)return;setSaving(true);setError("");setNotice("");try{const payload={request_id:requestID,period,recipe_id:recipe,percents,selling_price:price};const r=editing?await updateSellingSnapshot(editing.id,payload):await createSellingSnapshot(payload);setEditing(null);setSelected(r.data);setShowForm(false);setNotice("Versi baru tersimpan. Riwayat sebelumnya tetap utuh.");setRequestID(crypto.randomUUID());setPage(0);setRefresh(v=>v+1)}catch(e){setError(message(e))}finally{setSaving(false)}}
 function edit(row:SellingRow){setEditing(row);setRecipe(row.snapshot.source.recipe_id);setPercents(labels.map(label=>row.snapshot.calculation.components.find(c=>c.label===label)?.percent||"0"));setPrice(String(Math.round(Number(row.snapshot.calculation.selling_price))));setSelected(null);setShowForm(true);setError("");change();window.scrollTo({top:0,behavior:"smooth"})}
 async function remove(){if(!deleting||saving||deleting.used_in_orders)return;setSaving(true);setError("");try{await deleteSellingSnapshot(deleting.id);if(editing?.id===deleting.id){setEditing(null);setShowForm(false)}setSelected(null);setDeleting(null);setNotice("Harga penjualan dihapus.");setPage(0);setRefresh(v=>v+1)}catch(e){setError(message(e));setDeleting(null)}finally{setSaving(false)}}
 async function toggleActive(){if(!statusTarget||saving)return;setSaving(true);setError("");try{await setSellingSnapshotActive(statusTarget.id,!statusTarget.active);setSelected(null);setStatusTarget(null);setNotice(statusTarget.active?"Harga dinonaktifkan.":"Harga diaktifkan. Versi lain untuk resep ini otomatis nonaktif.");setRefresh(v=>v+1)}catch(e){setError(message(e));setStatusTarget(null)}finally{setSaving(false)}}
 async function exportExcel(){if(exporting)return;setExporting(true);setError("");try{const count=await exportSellingPrices(period);setNotice(`${count} versi harga berhasil diekspor.`)}catch(e){setError(e instanceof Error&&!isAxiosError(e)?e.message:message(e))}finally{setExporting(false)}}
 function change(){setRequestID(crypto.randomUUID());setNotice("")}
 return <div className="flex min-h-screen bg-[var(--color-brand-cream)]"><Sidebar isOpen={sidebar} onClose={()=>setSidebar(false)}/><section className="min-w-0 flex-1"><Navbar onMenuClick={()=>setSidebar(true)}/><main className="p-5 sm:p-8"><header className="mb-6"><Calculator className="mb-3 text-[var(--color-brand-primary)]"/><h1 className="font-serif text-3xl font-bold">HPP Harga Penjualan</h1><p className="mt-2 text-stone-600">Hitung biaya tambahan dan harga jual. Setiap versi menyimpan HPP serta persentase saat disimpan.</p></header><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><label className="block max-w-xs font-semibold">Periode bulan<input type="month" min="2000-01" value={period} disabled={saving} onChange={e=>{if(e.target.value){setPeriod(e.target.value);change()}}} className={`${input} mt-2`}/></label><div className="flex flex-wrap gap-3"><button type="button" disabled={exporting||saving||loadingHistory||total===0} onClick={()=>void exportExcel()} className="inline-flex items-center gap-2 rounded-xl border border-[var(--color-brand-primary)] bg-white px-5 py-3 font-semibold text-[var(--color-brand-primary)] disabled:opacity-40"><Download size={18}/>{exporting?"Mengekspor…":"Export Excel"}</button>{canCreate&&<button type="button" disabled={saving} onClick={()=>{setEditing(null);setRecipe("");setPrice("");setShowForm(v=>!v);change()}} aria-expanded={showForm} className="inline-flex items-center gap-2 rounded-xl bg-[var(--color-brand-primary)] px-5 py-3 font-semibold text-white disabled:opacity-40">{showForm?<X size={18}/>:<Plus size={18}/>} {showForm?"Tutup form":"Tambah harga penjualan"}</button>}</div></div>{error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{notice&&<p role="status" className="mb-4 rounded-xl bg-green-50 p-4 text-green-800">{notice}</p>}
 {(canCreate||canEdit)&&showForm&&<section className="mb-6 rounded-2xl border border-stone-200 bg-white p-5"><h2 className="mb-4 text-xl font-bold">{editing?"Edit harga penjualan · simpan sebagai versi baru":"Perhitungan baru"}</h2><div className="grid gap-5 lg:grid-cols-2"><div><label className="block font-semibold">Resep menu<select className={`${input} mt-2`} value={recipe} disabled={saving||!!editing} onChange={e=>{setRecipe(e.target.value);setPrice(sources.find(s=>s.recipe_id===e.target.value)?String(Math.round(Number(sources.find(s=>s.recipe_id===e.target.value)?.price))):"");change()}}><option value="">Pilih resep menu</option>{editing&&!sources.some(s=>s.recipe_id===recipe)&&<option value={recipe}>{editing.snapshot.source.product_name} · {editing.snapshot.source.version}</option>}{sources.map(s=><option key={s.recipe_id} value={s.recipe_id}>{s.category_name} · {s.product_name} · {s.version}</option>)}</select></label><div className="mt-4 grid grid-cols-2 gap-3">{labels.map((label,i)=><label key={label} className="text-sm font-semibold">{label} (%)<input type="number" min="0" max="100" step="0.000001" disabled={saving} value={percents[i]} onChange={e=>{setPercents(p=>p.map((v,j)=>j===i?e.target.value:v));change()}} className={`${input} mt-1`}/></label>)}</div><label className="mt-4 block font-semibold">Harga jual (Rp)<input type="text" inputMode="numeric" autoComplete="off" disabled={saving} value={price===""?"":new Intl.NumberFormat("id-ID",{maximumFractionDigits:0}).format(Number(price))} onChange={e=>{setPrice(e.target.value.replace(/[^0-9]/g,""));change()}} className={`${input} mt-2`}/></label><p className="mt-4 text-sm text-stone-500">Setiap komponen = HPP resep × persen ÷ 100. Total HPP = HPP resep + semua komponen. Surplus = harga jual − total HPP. Angka ditampilkan bulat; perhitungan menyimpan presisi asli.</p><p className="mt-2 text-sm text-stone-500">{editing?"Edit memakai HPP yang tersimpan pada versi ini. Versi sebelumnya tetap utuh.":"Versi baru memakai harga bahan aktif saat ini, termasuk saat memilih periode lain."}</p><button disabled={!valid||saving||loadingCost} onClick={()=>void save()} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[var(--color-brand-primary)] px-5 py-3 font-semibold text-white disabled:opacity-40"><Save size={18}/>{saving?"Menyimpan…":"Simpan versi baru"}</button></div><div className="overflow-hidden rounded-xl border">{loadingCost?<p className="p-5">Memuat HPP…</p>:valid?<Breakdown data={preview}/>:<p className="p-5 text-stone-500">{cost&&!cost.complete?`HPP belum lengkap: ${cost.issues.join("; ")}`:"Pilih resep dan isi persentase serta harga jual untuk melihat perhitungan."}</p>}</div></div></section>}
 <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white">
  <div className="border-b p-5"><h2 className="text-xl font-bold">Harga penjualan · {period}</h2><p className="mt-1 text-sm text-stone-500">{total} versi tersimpan. Pilih Detail untuk melihat persentase dan rincian HPP.</p></div>
  <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm">
   <thead className="bg-[var(--color-brand-surface)] text-stone-600"><tr>{["Menu","Kategori","Resep","Versi harga","HPP resep","Total HPP","Harga jual","Surplus","Status","Disimpan","Aksi"].map(label=><th key={label} scope="col" className={`whitespace-nowrap p-4 ${["HPP resep","Total HPP","Harga jual","Surplus"].includes(label)?"text-right":""}`}>{label}</th>)}</tr></thead>
   <tbody>{loadingHistory?<tr><td colSpan={11} className="p-10 text-center text-stone-500">Memuat harga tersimpan…</td></tr>:history.length?history.map(row=>{
    const {source,calculation}=row.snapshot;
    return <tr key={row.id} className={`border-t ${selected?.id===row.id?"bg-green-50":"hover:bg-stone-50"}`}>
     <td className="p-4 font-semibold">{source.product_name}</td><td className="p-4">{source.category_name}</td><td className="p-4">{source.version}</td><td className="p-4">{row.revision}</td>
     <td className="whitespace-nowrap p-4 text-right tabular-nums">{money(calculation.base_hpp)}</td><td className="whitespace-nowrap p-4 text-right tabular-nums">{money(calculation.total_hpp)}</td><td className="whitespace-nowrap p-4 text-right font-bold tabular-nums">{money(calculation.selling_price)}</td><td className={`whitespace-nowrap p-4 text-right font-semibold tabular-nums ${Number(calculation.surplus)<0?"text-red-700":"text-green-800"}`}>{money(calculation.surplus)}</td>
     <td className="p-4"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${row.active?"bg-green-50 text-green-700":"bg-stone-100 text-stone-500"}`}>{row.active?"Aktif":"Nonaktif"}</span></td><td className="whitespace-nowrap p-4 text-stone-500">{new Date(row.created_at).toLocaleString("id-ID")}</td><td className="whitespace-nowrap p-4"><button type="button" onClick={()=>setSelected(selected?.id===row.id?null:row)} aria-expanded={selected?.id===row.id} aria-label={`Detail ${source.product_name}, versi harga ${row.revision}`} title="Detail" className="inline-flex rounded-lg p-2 text-[var(--color-brand-primary)] hover:bg-green-50"><Eye size={18}/></button>{canEdit&&<button type="button" disabled={saving} onClick={()=>edit(row)} title="Edit" aria-label={`Edit ${source.product_name}, versi harga ${row.revision}`} className="inline-flex rounded-lg p-2 text-[var(--color-brand-primary)] hover:bg-green-50 disabled:opacity-40"><Pencil size={18}/></button>}{canEdit&&<button type="button" disabled={saving} onClick={()=>setStatusTarget(row)} title={row.active?"Nonaktifkan":"Aktifkan"} aria-label={`${row.active?"Nonaktifkan":"Aktifkan"} harga ${source.product_name}`} className={`inline-flex rounded-lg p-2 hover:bg-stone-100 disabled:opacity-40 ${row.active?"text-green-700":"text-stone-500"}`}><Power size={18}/></button>}{canDelete&&<button type="button" disabled={saving||row.used_in_orders} onClick={()=>setDeleting(row)} title={row.used_in_orders?"Sudah dipakai pesanan, tidak bisa dihapus":"Delete"} aria-label={`Delete ${source.product_name}, versi harga ${row.revision}`} className="inline-flex rounded-lg p-2 text-red-700 hover:bg-red-50 disabled:opacity-40"><Trash2 size={18}/></button>}</td>
    </tr>
   }):<tr><td colSpan={11} className="p-10 text-center text-stone-500">Belum ada harga penjualan tersimpan pada bulan ini.</td></tr>}</tbody>
  </table></div>
  <footer className="flex flex-wrap items-center justify-between gap-3 border-t p-4 text-sm text-stone-500"><span>Halaman {page+1} dari {Math.max(1,Math.ceil(total/50))}</span><div className="flex gap-3"><button className="rounded border p-2 disabled:opacity-40" disabled={page===0||loadingHistory} onClick={()=>{setPage(p=>p-1);setSelected(null)}}>Sebelumnya</button><button className="rounded border p-2 disabled:opacity-40" disabled={(page+1)*50>=total||loadingHistory} onClick={()=>{setPage(p=>p+1);setSelected(null)}}>Berikutnya</button></div></footer>
 </section>
 {selected&&<dialog ref={detailDialog} aria-labelledby="selling-price-detail-title" onCancel={e=>{e.preventDefault();setSelected(null)}} onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}} className="fixed inset-0 m-auto max-h-[90dvh] w-[calc(100%-2rem)] max-w-3xl overflow-y-auto rounded-2xl border border-stone-200 bg-white p-5 shadow-2xl backdrop:bg-black/50 backdrop:backdrop-blur-sm"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 id="selling-price-detail-title" className="text-xl font-bold">{selected.snapshot.source.product_name} · Versi harga {selected.revision}</h2><p className="mt-1 text-sm text-stone-500">{selected.period} · {selected.snapshot.source.category_name} · {selected.snapshot.source.version}</p></div><button type="button" onClick={()=>setSelected(null)} aria-label="Tutup detail harga" className="rounded-lg border p-2"><X size={18}/></button></div><div className="max-w-3xl overflow-hidden rounded-xl border"><Breakdown data={selected.snapshot.calculation}/></div><p className="mt-3 text-sm text-stone-500">Angka ini disimpan saat versi dibuat. Perubahan resep dan persentase berikutnya tidak mengubahnya.</p><footer className="mt-5 flex justify-end border-t pt-4"><button type="button" onClick={()=>setSelected(null)} className="rounded-xl bg-[var(--color-brand-primary)] px-5 py-2 font-semibold text-white">Tutup</button></footer></dialog>}
 <ConfirmDialog open={!!deleting} title="Hapus harga penjualan?" message={`Hapus ${deleting?.snapshot.source.product_name||""} versi ${deleting?.revision||""} dari tabel harga?`} confirmText="Delete" tone="danger" submitting={saving} onCancel={()=>setDeleting(null)} onConfirm={()=>void remove()}/>
 <ConfirmDialog open={!!statusTarget} title={statusTarget?.active?"Nonaktifkan harga?":"Aktifkan harga?"} message={statusTarget?.active?"Harga ini tidak lagi menjadi harga aktif untuk resep ini.":"Harga ini menjadi harga aktif untuk resep ini. Versi harga lainnya otomatis nonaktif."} confirmText={statusTarget?.active?"Nonaktifkan":"Aktifkan"} submitting={saving} onCancel={()=>setStatusTarget(null)} onConfirm={()=>void toggleActive()}/>
 </main></section></div>;
}
