import {useEffect,useState,type FormEvent} from "react";
import {X,ChevronDown} from "lucide-react";
import {isAxiosError} from "axios";
import {createProduct,updateProduct,type Product} from "../../api/product.api";
import type {Category} from "../../api/category.api";
export default function CreateMenuModal({categories,initialCategory,onClose,onCreated,product}:{product?:Product;categories:Category[];initialCategory:string;onClose:()=>void;onCreated:(category:string,name:string)=>void}){
 const [category,setCategory]=useState(product?.category_id ?? initialCategory),[name,setName]=useState(product?.name ?? ""),[description,setDescription]=useState(product?.description ?? ""),[image,setImage]=useState(product?.image_url ?? ""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous}},[]);
 useEffect(()=>{const listener=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!saving)onClose()};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener)},[saving,onClose]);
 async function submit(event:FormEvent){event.preventDefault();if(saving)return;setError("");if(!category||name.trim().length<2){setError("Pilih kategori dan isi nama menu minimal 2 karakter.");return}setSaving(true);try{const payload={category_id:category,name:name.trim(),description:description.trim(),image_url:image.trim(),price:product?.price ?? "0",active:product?.active ?? true};if(product)await updateProduct(product.product_id,payload);else await createProduct(payload);onCreated(category,name.trim())}catch(e){setError(isAxiosError<{message?:string}>(e)?e.response?.data?.message||"Gagal menyimpan menu.":"Gagal menyimpan menu.")}finally{setSaving(false)}}
 const inputClass="mt-2 w-full rounded-xl border border-stone-300 px-3 py-3 font-normal outline-none focus:border-[var(--color-brand-accent)] focus:ring-2 focus:ring-[var(--color-brand-accent)]/20 disabled:opacity-50";
 return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/40 p-4" onClick={()=>{if(!saving)onClose()}}><form onSubmit={submit} role="dialog" aria-modal="true" aria-labelledby="create-menu-title" className="max-h-[90dvh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white shadow-xl" onClick={e=>e.stopPropagation()}><header className="flex items-center justify-between border-b p-5"><h2 id="create-menu-title" className="text-xl font-bold">{product?"Ubah menu":"Tambah menu"}</h2><button type="button" disabled={saving} onClick={onClose} aria-label="Tutup tambah menu" className="rounded-lg p-2 disabled:opacity-40"><X size={20}/></button></header><div className="space-y-4 p-5"><label className="block text-sm font-semibold">Nama menu<input autoFocus required minLength={2} maxLength={100} value={name} disabled={saving} onChange={e=>setName(e.target.value)} className={inputClass}/></label><label className="block text-sm font-semibold">Kategori menu<span className="relative mt-2 block"><select required value={category} disabled={saving} onChange={e=>setCategory(e.target.value)} className="w-full appearance-none rounded-xl border border-stone-300 bg-white py-3 pl-3 pr-10 font-normal outline-none focus:border-[var(--color-brand-accent)]"><option value="">Pilih kategori menu</option>{categories.filter(row=>row.active||row.category_id===product?.category_id).map(row=><option key={row.category_id} value={row.category_id}>{row.name}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-stone-500"/></span></label><label className="block text-sm font-semibold">Deskripsi <span className="font-normal text-stone-400">(opsional)</span><textarea maxLength={255} value={description} disabled={saving} onChange={e=>setDescription(e.target.value)} className={`${inputClass} min-h-24`}/></label><label className="block text-sm font-semibold">URL gambar <span className="font-normal text-stone-400">(opsional)</span><input type="url" maxLength={500} value={image} disabled={saving} onChange={e=>setImage(e.target.value)} className={inputClass}/></label><p className="text-sm text-stone-500">Setelah menu dibuat, buka detail untuk menambahkan resep. Harga jual diatur di HPP Harga Penjualan.</p>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div><footer className="flex justify-end gap-3 border-t p-5"><button type="button" disabled={saving} onClick={onClose} className="rounded-xl border px-4 py-2.5 text-sm font-semibold disabled:opacity-40">Batal</button><button type="submit" disabled={saving||!category} className="rounded-xl bg-[var(--color-brand-primary)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{saving?"Menyimpan…":product?"Simpan perubahan":"Tambah menu"}</button></footer></form></div>
}
